### ISSUE TITLE
Problems with append option in DCD reporter

### ISSUE THREAD

**Issue by SimoneCnt** [pandegroup/openmm#1863] opened 2017-07-28 22:32 UTC
Hello,

I'm trying the append option of the DCD reporter -- without much success actually.
Here the test script I'm using:

    savfreq = 100
    totstep = 1000

    diala = testsystems.AlanineDipeptideImplicit()

    integrator = omm.LangevinIntegrator(300*u.kelvin, 1/u.picosecond, 1*u.femtosecond)
    simulation = app.Simulation(diala.topology, diala.system, integrator)

    simulation.context.setPositions(diala.positions)
    simulation.context.setVelocitiesToTemperature(300*u.kelvin)
    simulation.minimizeEnergy(maxIterations=1000)

    # Add DCD reporter
    simulation.reporters.append(app.DCDReporter("dyna1.dcd", savfreq, append=False))

    # Run MD - save 10 frames
    simulation.step(totstep)

    # Remove previous reporter and add a new one -- with append now
    simulation.reporters.pop(-1)
    simulation.reporters.append(app.DCDReporter("dyna1.dcd", savfreq, append=True))

    # Run MD - save other 10 frames
    simulation.step(totstep)

Running this I correctly obtain a dcd with 20 frames but:
 - The dcd header is not modified, so it shows 10 frames
 - The last 10 frames are not readable; e.g. VMD complains with:
    dcdplugin) Warning: DCD header claims 10 frames, file size indicates there are actually 20 frames
    dcdplugin) read_dcdstep: corruption or unrecognized file structure

Am I doing something wrong?
Is that one the "correct" way to remove a reporter? 

Thanks for the help.

**Comment by peastman** [comment] 2017-08-01 19:34
I just posted a PR to fix this: #1866.  Could you test it and verify it works for you?

This was caused by a strange, poorly documented behavior (or possibly just a bug) in Python file I/O.  When it opened the file to append, it specified the mode as `a+b`: append, allow reading as well as writing, binary mode.  And everything *seemed* to work.  I could read the file, modify it, and add to the end.  But in reality, it wasn't saving any changes made to the existing file content.  It was only appending, but not modifying what was already there.  It didn't throw an exception or anything to indicate there was a problem.  It just silently ignored all changes I made to the existing file content.  So yeah, I'd say it's a bug in Python.

Anyway, the fix was to instead specify the file mode as `r+b`.  With that change, it now seems to be working.

**Comment by SimoneCnt** [comment] 2017-08-01 20:18
Seems working also for me.
Thanks!

One note: if append is set to true but no file already exists the python interface correctly print an error and quit. This is fine, but then I have to add a switch in my code like:
    `` if this is the first run -> append=False``
     ``otherwise -> append=True``
It's not possible to add this switch directly inside the dcdreporter.py file like:
    ``if (append && file-does-not-exist) -> append=false``

**Comment by peastman** [comment] 2017-08-01 21:00
Thanks!  The fix is merged.

**Closed** 2017-08-01 21:00 UTC
