### ISSUE TITLE
Mixing CustomExternalForce with MonteCarloBarostat

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1854] opened 2017-07-05 16:05 UTC
We'd like to run some NPT simulations using `MonteCarloBarostat` with a protein or protein:ligand complex where the biomolecules have weak harmonic restraints on alpha carbons or heavy atoms so they don't drastically change conformation. The most obvious way to do this is to use `CustomExternalForce` to weakly restrain the positions to reference positions, but I'm worried this will cause `MonteCarloBarostat` moves that scale molecules (toward the origin?) to almost universally be rejected because the molecules will be displaced away from their reference positions. If there is only one biomolecule, moving it to the origin might eliminate this issue, but for a protein:ligand system, it doesn't seem like there is a way to avoid this issue. 

Any ideas on how we might be able to work around this? I suppose we could instead use a completely different kind of restraints (weak torsion restraints?), but I wonder if being able to specify which molecules should be included/excluded from the molecular scaling of `MonteCarloBarostat` might be a workable solution: By translating the protein:ligand complex to the origin of molecular scaling and excluding them from barostat proposals, we could still adjust the total system volume and have the waters equilibrate around the protein.

**Comment by peastman** [comment] 2017-07-05 18:18
If you only have restraints on one molecule, you could just translate your system so the center of that molecule is at the origin.  Then the barostat won't change it.

If you have restraints on multiple molecules then you have a different problem: rescaling the periodic box will necessarily change the positions of those molecules relative to each other, so restraining them to fixed positions will necessarily conflict with that.

**Comment by jchodera** [comment] 2017-07-05 21:10
> If you have restraints on multiple molecules then you have a different problem: rescaling the periodic box will necessarily change the positions of those molecules relative to each other, so restraining them to fixed positions will necessarily conflict with that.

That's exactly what I was worried about, but it is also the scenario that is most interest interesting.

Would it be sensible to think of how we could extend the `MonteCarloBarostat` to let the user optionally specify a subset of atoms should be *not* moved during calls to `kernel.getAs<ApplyMonteCarloBarostatKernel>().scaleCoordinates()`? The number of molecular centers used in the acceptance criteria should be altered as well.

For example, we could have `MonteCarloBarostat.freezeMolecule(atoms)` as a way to specify that this molecule should be frozen.

**Comment by jlmaccal** [comment] 2017-07-05 21:23
Why not just add dummy particles with no interaction and zero mass and then add bonds between the alpha carbons and the corresponding dummy particles?

**Comment by peastman** [comment] 2017-07-05 21:28
Good thought.  The positions of those dummy particles should get scaled along with the real particles, so they'll stay together.

**Comment by jchodera** [comment] 2017-07-05 22:18
Interesting! This might work for some of our uses, though I'm a bit worried about changing the number of atoms in the system because we would have to add these atoms to every nonbonded-like `Force` object in the `System`, and our alchemically-modified systems have a number of `NonbondedForce` and `CustomNonbondedForce` objects.

Would the barostat group the massless dummy particles together into the same "molecules" as their parent molecules?

Just some insight on why we're trying to do this: Part of the goal here is to assess several `CustomIntegrator`s on protein systems without having to deal with large-scale conformational changes. `CustomIntegrator` should deal with massless particles transparently (according to the docs) but I admit I haven't tested this. The other goal is to benchmark alchemical free energy calculation methods on systems where we don't have to worry about large-scale conformational changes.

**Comment by peastman** [comment] 2017-07-05 22:28
> Would the barostat group the massless dummy particles together into the same "molecules" as their parent molecules?

Assuming you have bonds connecting them to the corresponding real atoms, yes.

**Comment by jchodera** [comment] 2017-07-05 22:45
If I have a protein:ligand system, what if I added a `HarmonicBondForce` between the protein and ligand with a zero (or near-zero) spring constant? Wouldn't that make them a single molecule that would then be scaled together? If I kept the whole mess near the origin (centroid? center of mass?) then it wouldn't be moved when the barostat tries to scale molecules.

**Comment by peastman** [comment] 2017-07-05 22:51
Yes, that might work.  It scales the centroid.

**Comment by Lnaden** [comment] 2017-11-22 00:15
I'd like to revive this issue. We implemented this solution in YANK, however, were seeing some very troubling behavior and would like some help brainstorming solutions. 

As a brief recap: We want to restrain the heavy atoms some solute to a physical location in space. This way we can confine the sampling degrees of freedom to reduce conformational changes. The suggestion here was to translate the solute's centroid to the origin and restrain around it to minimize the energy penalty rescaling the positions would have since the restrained "positions" in the `CustomExternalForce` are just general parameter floats of each restrained atom and the `Force` object itself does not scale those parameters.

Now for the problems. The implementation of this (posted in the code block below) yields the following plot for a simple system like Alanine Dipeptide.

![Alanine Dipeptide](https://i.imgur.com/7bugwO9.png)

Which is okay, but as you can see in the restrained system (bottom plot), there are energy spikes as you can see from the energy curves (blue).

However, the problem gets worse the larger the molecule is (somewhat expected). The change in volume causes massive spikes in the potential energy and its most certainly not sampling the correct distribution any more. This is DHFR for example

![DHFR](https://i.imgur.com/ZRrnmeI.png)

I think the problem is that restraining to absolute points in space causes a problem because the scale of that "absolute" point changes as the box vectors do, especially if any of the points are periodically wrapped, which will happen since some will be at -X/-Y/-Z coordinates, which can warp and deform the molecule. @jchodera has a movie of this, but its hard to see as the molecule jumps around the box too much so its hard to see unless you frame-by-frame

Thoughts and thanks in advance

```python
import simtk.openmm as mm
import simtk.openmm.app as app
import numpy as np
import openmmtools as mmtools
import simtk.unit as unit
from copy import deepcopy

# Parameters
T = 300 * unit.kelvin
P = 1 * unit.atmosphere
kT = T * unit.BOLTZMANN_CONSTANT_kB * unit.AVOGADRO_CONSTANT_NA
sigma = 3 *unit.angstrom
nsteps_per_write = 500
total_steps = 1000

# Test System
test = mmtools.testsystems.DHFRExplicit()
solute = list(range(2489))
pos = test.positions
positions = np.zeros([len(pos), 3]) * unit.nanometer
for idx, p_i in enumerate(pos):
    positions[idx, :] = p_i

# Translate solute to geometric center on origin
centroid = np.mean(positions[solute, :] / positions.unit, axis=0) * positions.unit
positions -= centroid

# Create a CustomExternalForce to restrain all atoms.
K = kT / sigma**2  # Spring constant.
restraint_force = mm.CustomExternalForce('(K/2)*((x-x0)^2 + (y-y0)^2 + (z-z0)^2)')
# Adding the spring constant as a global parameter allows us to turn it off if desired
restraint_force.addGlobalParameter('K', K)
restraint_force.addPerParticleParameter('x0')
restraint_force.addPerParticleParameter('y0')
restraint_force.addPerParticleParameter('z0')
for index in solute:
    parameters = positions[index, :].value_in_unit_system(unit.md_unit_system)
    restraint_force.addParticle(index, parameters)

unrestrained_system = test.system
# Remove CoM force
for index, force in enumerate(unrestrained_system.getForces()):
    if isinstance(force, mm.CMMotionRemover):
        unrestrained_system.removeForce(index)
        break
# Add barostat
barostat = mm.MonteCarloBarostat(P, T)
unrestrained_system.addForce(barostat)
# Create restraint system
restrained_system = deepcopy(unrestrained_system)
restrained_system.addForce(restraint_force)

systems = {"Unrestrained": unrestrained_system,
           "Restrained": restrained_system}

# Run with reporter
for name, system in systems.items():
    integrator = mm.LangevinIntegrator(T, 5/unit.picosecond, 2 * unit.femtosecond)
    sim = app.Simulation(test.topology, system, integrator)
    sim.context.setPositions(positions)
    reporter = app.StateDataReporter('{}_V_U.csv'.format(name), nsteps_per_write, potentialEnergy=True, volume=True)
    sim.reporters.append(reporter)
    sim.minimizeEnergy()
    for _ in range(total_steps):
        sim.step(nsteps_per_write)
    del sim, integrator

```

P.S.: I know the minimization happens after the restraint in this code, but I just tested with minimizing first., then restraining and repeating that the same symptoms appear.

**Comment by jchodera** [comment] 2017-11-22 20:37
Any insight into this @peastman? I think we're out of ideas for a workaround that will let us weakly restrain some atoms in space while using the barostat. There additionally might be something weird with using `CustomExternalForce` with negative positions and the barostat simultaneously.

Other ideas would be to extend the barostat API with some simple enhancements, such as
1. **Add a flag that omits molecules restrained with a `CustomExternalForce` from the barostat scaling.** This would allow a single flag to be set that would exclude atoms involved in `CustomExternalForce` interactions (and their corresponding molecules) from scaling.
2. **Specify a list of atoms to define the center around which the box is scaled.** For example, we could specify the macromolecule atoms, and the barostat would (1) compute the center to scale about using these atoms, and (2) avoid trying to scale those atoms.
3. **Specify a list of atoms to omit from the scaling.** This would allow us to specify the macromolecule should not be scaled. This would likely reduce overall acceptance rates though, since solvent would be scaled into the macromolecule.

**Comment by peastman** [comment] 2017-11-22 22:46
What happens if you just replace

```python
restraint_force = mm.CustomExternalForce('(K/2)*((x-x0)^2 + (y-y0)^2 + (z-z0)^2)')
```

with

```python
restraint_force = mm.CustomExternalForce('(K/2)*periodicdistance(x, y, z, x0, y0, z0)^2')
```

**Comment by jchodera** [comment] 2017-11-23 04:41
Volume trajectory looks much better:
![image](https://user-images.githubusercontent.com/3656088/33159179-9fa1578e-cfde-11e7-8483-996bf28b2f7c.png)
The distribution is slightly different, but that might be expected with the presence of a restraint:
![image](https://user-images.githubusercontent.com/3656088/33159168-8207d7fc-cfde-11e7-93a6-21e7c4caf0da.png)

**Comment by jchodera** [comment] 2017-11-24 17:34
For comparison, here are the same plots without using `periodicdistance`:
![image](https://user-images.githubusercontent.com/3656088/33220049-895f23c6-d0fa-11e7-8406-934e0809a698.png)
![image](https://user-images.githubusercontent.com/3656088/33220058-9145084e-d0fa-11e7-8363-3e6152a5f4d2.png)
@Lnaden: I'll create a PR to switch our code to use `periodicdistance`.

**Comment by peastman** [comment] 2017-11-24 20:34
It uses whatever box dimensions are currently specified.  A system is considered to be periodic if any force applies periodic boundary conditions.  So if the CustomExternalForce uses `periodicdistance()`, then by definition it's a periodic system.

**Comment by jchodera** [comment] 2017-11-24 20:36
Thanks for the clarification!

**Comment by Lnaden** [comment] 2017-11-28 13:21
I think with the changes we made in choderalab/openmmtools#310, we can close this issue as `periodicdistance` is a solution, and something people should be careful when anchoring to specific points in space.

**Closed** 2017-11-28 16:38 UTC

**Comment by jchodera** [comment] 2017-11-28 16:39
Peter had already put a warning in the [API docs](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html#simtk.openmm.openmm.CustomExternalForce) that I had totally missed:
> Special care is needed in systems that use periodic boundary conditions. In that case, each particle really represents an infinite set of particles repeating through space. The variables x, y, and z contain the coordinates of one of those periodic copies, but there is no guarantee about which. It might even change from one time step to the next. You can handle this situation by using the function periodicdistance(x1, y1, z1, x2, y2, z2), which returns the minimum distance between periodic copies of the points (x1, y1, z1) and (x2, y2, z2). For example, the force given above would be rewritten as
```C++
CustomExternalForce* force = new CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2");
```

**Comment by JoaoRodrigues** [comment] 2019-04-29 23:43
Hi all,

Just to clarify. If we a system with TWO or more molecules that we wish to restrain using harmonic restraints AND we are using a barostat (any?), this will cause problems? Or does the `periodicdistance` trick work for all cases?

I am having extremely weird results in some equilibrations of a multi-protein system with a barostat and think this might be culprit, since not using restraints makes the problem go away.

**Comment by peastman** [comment] 2019-04-30 00:37
Could you describe what the problem is?  periodicdistance() does what it does, independent of how many molecules are in your system.  What's the exact form of your restraints, and what's the significance of having multiple molecules?

Perhaps the problem is that you need the reference positions to scale with the box?  If so, this discussion might be relevant: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10049&p=0&start=0&view=&sid=b844250e55b14682fb21b5f66a4d810f

**Comment by JoaoRodrigues** [comment] 2019-04-30 00:43
Without wanting to hijack the thread, the problem is the following. I have a system composed of two proteins (dimer), a membrane (POPC), water and ions. To equilibrate the system, I'd like to keep the positions of the protein atoms restrained to their original/initial values. I am having trouble when I go from NVT to NPT, which I assume is because of the barostat and rescaling. The system keeps blowing up and/or I have a very very weird behavior of the box (gets squished). If I do not run with restraints, I bypass at least the blowing up problem (not sure about the squishing of the box). I'm trying the dummy atom approach and will report back.

**Comment by JoaoRodrigues** [comment] 2019-04-30 02:03
Update: indeed, using dummy atoms to restraint positions works very well. Thanks!

**Comment by peastman** [comment] 2019-04-30 02:12
Great, glad that works!
