### ISSUE TITLE
deserializeState hangs on bad xml files

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#479] opened 2014-06-10 10:13 UTC
I came across a corrupted state.xml where one of the fields ended up looking like:

<PoNULNULNULàÿÿÿ"3.10002>

But the end result is that the deserializer goes into an infinite loop. I'm wondering if we should guard ourselves against badly formed XML files and have some exception be thrown.

**Comment by peastman** [comment] 2015-02-20 19:35
This issue might be fixed, now that we've switched from TinyXML to irrXML.  Does anyone have an example of a file that produced this problem?

**Comment by kyleabeauchamp** [comment] 2015-02-20 19:43
I did a brief look and couldn't find any bad files on my FAH server.  I don't think I can find any examples of this without knowing exactly what to look for.

**Comment by peastman** [comment] 2015-06-24 20:58
Since we can't reproduce this, and since there's no reason to expect irrXML to have the same bugs as TinyXML, I'm going to close the issue.  If anyone finds a bad XML file that still causes problems, let's open a new issue on it.

**Closed by peastman** 2015-06-24 20:58 UTC
