### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1782] opened 2017-04-10 02:08 UTC
What do you think about (1) organizing the `examples/` directory a bit, and (2) including the `run_benchmark.sh` and `benchmark.py` scripts in a separate `benchmarks/` directory to make it easier to find?

**Comment by peastman** [comment] 2017-04-10 16:53
Both are reasonable.  But this is a duplicate of #730, so I'm going to close it.  Let's keep the discussion in one place.

**Closed by peastman** 2017-04-10 16:53 UTC

**Comment by jchodera** [comment] 2017-04-11 00:27
Whoops, sorry!
