### ISSUE TITLE
Funny behavior with force groups

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2181] opened 2018-10-01 14:27 UTC
This script simply integrates DHFR in explicit solvent with a `V R O R V` Langevin integrator.
First, all `Force` objects are in the same force group.
Next, everything but `NonbondedForce` is moved to force group 1 and the force groups are integrated as `V0 V1 R O R V1 V0`, which should be *identical* to the first case (to within numerical precision errors).
```python
#!/usr/bin/env python

import time
from simtk import unit, openmm
from openmmtools import testsystems

t = testsystems.DHFRExplicit(hydrogenMass=3.0*unit.amu)
system, positions = t.system, t.positions

def time_system(system, integrator, positions):
    context = openmm.Context(system, integrator)
    context.setPositions(positions)
    integrator.step(10)

    nsteps = 5000
    print('Integrating %d steps' % nsteps)
    initial_time = time.time()
    integrator.step(nsteps)
    potential = context.getState(getEnergy=True).getPotentialEnergy()
    final_time = time.time()
    elapsed_time = final_time - initial_time
    timestep = integrator.getStepSize()
    ns_per_day = (nsteps * timestep) / (elapsed_time * unit.seconds) * (unit.day) / unit.nanoseconds
    print('Integration took %8.3f s : %8.3f ns / day : energy %8.3f kcal/mol' % (elapsed_time, ns_per_day, potential / unit.kilocalories_per_mole))

    del context, integrator

temperature = 300 * unit.kelvin
collision_rate = 1.0 / unit.picoseconds

from openmmtools import integrators

# Run simulation with all forces belonging to same group
print('Same force group')
timestep = 4.0 * unit.femtoseconds
splitting = 'V R O R V'
integrator = integrators.LangevinIntegrator(temperature, collision_rate, timestep, splitting=splitting)
time_system(system, integrator, positions)

# Move valence terms to force group 1
for force in system.getForces():
    if force.__class__.__name__ != 'NonbondedForce':
        force.setForceGroup(1)
    else:
        reference_nonbonded_force = force

# Run equivalent simulation with forces split into groups, but should be the same
print('Different force groups')
timestep = 4.0 * unit.femtoseconds
splitting = 'V0 V1 R O R V1 V0'
integrator = integrators.LangevinIntegrator(temperature, collision_rate, timestep, splitting=splitting)
time_system(system, integrator, positions)
```
This produces the output:
```
Same force group
Integrating 5000 steps
Integration took   11.424 s :  151.265 ns / day : energy -72165.349 kcal/mol
Different force groups
Integrating 5000 steps
Integration took    1.822 s :  948.254 ns / day : energy 1099715946678635520.000 kcal/mol
```
I realize this depends on our `openmmtools.integrators.LanegvinIntegrator`, but the bug can probably be reproduced with a much simpler code. @andrrizzi might be able to post a simpler version.

cc: #2171

**Comment by andrrizzi** [comment] 2018-10-01 14:30
> @andrrizzi might be able to post a simpler version.

Working on it!

**Comment by andrrizzi** [comment] 2018-10-01 15:33
Here's a slightly simpler code.
```python
#!/usr/bin/env python

from simtk import unit, openmm
from openmmtools import testsystems


def read_integrator(file_path):
    with open(file_path, 'r') as f:
        integrator = openmm.XmlSerializer.deserialize(f.read())
    return integrator


def propagate(system, positions, integrator):
    n_steps = 100
    context = openmm.Context(system, integrator)
    context.setPositions(positions)
    integrator.step(n_steps)
    potential = context.getState(getEnergy=True).getPotentialEnergy()
    del context, integrator
    return potential


t = testsystems.DHFRExplicit(hydrogenMass=3.0*unit.amu)
system, positions = t.system, t.positions

# Run simulation with all forces belonging to same group.
integrator = read_integrator('integrator.xml')
potential = propagate(system, positions, integrator)
print('Potential after propagation: {}'.format(potential))

# Move valence terms to force group 1
for force in system.getForces():
    if force.__class__.__name__ != 'NonbondedForce':
        force.setForceGroup(1)
    else:
        reference_nonbonded_force = force

# Update velocities separately for the two force groups.
integrator = read_integrator('split_integrator.xml')
potential = propagate(system, positions, integrator)
print('Potential after propagation with force group splitting: {}'.format(potential))
```
results in
```
Potential after propagation: -328880.5698418098 kJ/mol
Potential after propagation with force group splitting: 43357441228397.18 kJ/mol
```
I have attached the XML serialization of the integrators, but here's their pretty print.
```
integrator
----------
step      0 : allow forces to update the context state
step      1 : if(has_kT_changed = 1):
step      2 :    sigma <- sqrt(kT/m)
step      3 :    has_kT_changed <- 0
step      4 : end
step      5 : v <- v + (dt / 2) * f / m
step      6 : constrain velocities
step      7 : x <- x + ((dt / 2) * v)
step      8 : x1 <- x
step      9 : constrain positions
step     10 : v <- v + ((x - x1) / (dt / 2))
step     11 : constrain velocities
step     12 : v <- (a * v) + (b * sigma * gaussian)
step     13 : constrain velocities
step     14 : x <- x + ((dt / 2) * v)
step     15 : x1 <- x
step     16 : constrain positions
step     17 : v <- v + ((x - x1) / (dt / 2))
step     18 : constrain velocities
step     19 : v <- v + (dt / 2) * f / m
step     20 : constrain velocities


split_integrator
----------------
step      0 : allow forces to update the context state
step      1 : if(has_kT_changed = 1):
step      2 :    sigma <- sqrt(kT/m)
step      3 :    has_kT_changed <- 0
step      4 : end
step      5 : v <- v + ((dt / 2) * f0 / m)
step      6 : constrain velocities
step      7 : v <- v + ((dt / 2) * f1 / m)
step      8 : constrain velocities
step      9 : x <- x + ((dt / 2) * v)
step     10 : x1 <- x
step     11 : constrain positions
step     12 : v <- v + ((x - x1) / (dt / 2))
step     13 : constrain velocities
step     14 : v <- (a * v) + (b * sigma * gaussian)
step     15 : constrain velocities
step     16 : x <- x + ((dt / 2) * v)
step     17 : x1 <- x
step     18 : constrain positions
step     19 : v <- v + ((x - x1) / (dt / 2))
step     20 : constrain velocities
step     21 : v <- v + ((dt / 2) * f1 / m)
step     22 : constrain velocities
step     23 : v <- v + ((dt / 2) * f0 / m)
```
[force_groups_error.zip](https://github.com/pandegroup/openmm/files/2434561/force_groups_error.zip)

**Comment by peastman** [comment] 2018-10-01 16:07
Thanks!  I'll take a look.  Which platform are you using?  Does the same error occur on all platforms?

**Comment by andrrizzi** [comment] 2018-10-01 16:40
Whoops! Sorry, I didn't include it explicitly in the script, but I generated the output using CUDA.

**Comment by jchodera** [comment] 2018-10-01 17:49
It does seem to happen on all the platforms I tested:
```
[chodera@lilac:chodera]$ python force-group-bug.py
Same force group
Integrating 500 steps
Integration took    1.158 s :  149.251 ns / day : energy -74688.712 kcal/mol
Different force groups for platform CPU
Integrating 500 steps
Integration took  209.988 s :    0.823 ns / day : energy 53643286977199032.000 kcal/mol
Different force groups for platform CUDA
Integrating 500 steps
Integration took    0.204 s :  846.971 ns / day : energy 988941661220322944.000 kcal/mol
Different force groups for platform OpenCL
Integrating 500 steps
Integration took    1.577 s :  109.545 ns / day : energy 28384998489614794752.000 kcal/mol
```

**Comment by peastman** [comment] 2018-10-02 19:01
Here's your problem:

```python
for force in system.getForces():
    print(force, force.getForceGroup())
```

prints out

```
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x1091dd090> > 0
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x1145ed570> > 1
<simtk.openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x1145ed960> > 2
<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x1145ed420> > 11
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x1145ed3c0> > 0
```

Your forces are initially in lots of different groups.  The first integrator doesn't care about that.  For the second integrator, you loop over all forces and set everything *except* the NonbondedForce to group 1.  The NonbondedForce gets left in group 11.  But your integrator expects it to be in group 0.

**Comment by andrrizzi** [comment] 2018-10-02 20:39
Ah! Sorry about that. It looks like we load the prmtop/inpcrd files with ParmEd in that testsystem, and ParmEd divides the forces into different groups when it is created. Thanks for figuring this out! I'll keep trying to have a minimal script to reproduce the 7.3 NaN problem then. Feel free to close this.

**Closed** 2018-10-02 20:41 UTC

**Comment by jchodera** [comment] 2018-10-02 22:33
Good catch, @peastman!

@andrrizzi : Can you file an issue on the openmm issue tracker for us to change that behavior and make sure all force groups are set to 0 for all `openmmtools.testsystems`?

**Comment by peastman** [comment] 2018-10-02 23:14
You mean the openmmtools issue tracker?

**Comment by jchodera** [comment] 2018-10-03 12:15
Whoops, yes!
