### ISSUE TITLE
CPU and CUDA produce different energy values

### ISSUE THREAD

**Issue by isjoung** [pandegroup/openmm#1476] opened 2016-05-02 01:34 UTC
This is a branched issue from #1434.

 This is the test code.

```python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
import cPickle
import parmed as pmd

platform_name = 'CPU'
#platform_name = 'CUDA'

with open('input.dat','rb') as f:
    system, prmtop, inpcrd = cPickle.load(f)
prmtop.DFIRE_FORCE_GROUP = 13

integrator = mm.LangevinIntegrator(300.0*unit.kelvin, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)
platform = mm.Platform.getPlatformByName(platform_name)
simulation = app.Simulation(prmtop.topology, system, integrator, platform)
context = simulation.context
context.setPositions(inpcrd.positions)

dene_dict = pmd.openmm.energy_decomposition(prmtop, context)
print(dene_dict)
```

CPU result:
{'angle': nan, 'dfire': 3797.767595666509, 'nonbonded': 56336477937418.76, 'bond': 26636613518.118565, 'total': nan, 'dihedral': 2858.1764757513142}

CUDA result:
{'angle': 104374.10686638913, 'dfire': -6.71629646532508e+36, 'nonbonded': 56336477937205.82, 
'bond': 26636612264.855366, 'total': nan, 'dihedral': nan}

Three terms are different depending on platform: angle, dfire, dihedral

The input data can be downloaded from: 
https://drive.google.com/file/d/0B2y-WOTYohWabExyV1NtSHVlU2c/view?usp=sharing

**Comment by isjoung** [comment] 2016-05-02 02:22
FYI, dfire energy is only dependent on atomic distances and there is no singular point in energy value. There are 94,830 bonds in it. The lowest energy point is -10.57. Even if every bond has the lowest energy value (94830*-10.57), the total energy is only -1.0e+6. The dfire energy by CUDA (-6.71629646532508e+36) is a nonsense.

**Comment by peastman** [comment] 2016-05-02 16:40
Never mind the dfire term: half your energy components are nan, and most of the others are ridiculous values.  Something is clearly messed up in that.  For example, are you sure the positions you're setting are correct?

**Comment by isjoung** [comment] 2016-05-02 16:51
I know that the coordinates are completely messy, but incorrect energy is surly a serious problem. My goal is finding many lower energy conformations. I intentionally perturb coordinates wildly. However, unfortunately, the weird energy guide me to the ugly spot. Actually, the dfire energy was similar to the one by CPU platform, but energy minimizatoin resulted in the weird number. Then the two energy values by different platform became completely different.

**Comment by peastman** [comment] 2016-05-02 17:54
It's not just a question of the coordinates being messy.  "Nan" stands for "not a number".  It's what you get when you try to compute something completely crazy, like 0/0 or infinity-infinity.

This has to do with how computers represent numbers.  In the world of pure mathematics, a number is an exact thing.  It has an infinitely precise value, and there's no upper or lower limit on what numbers are possible.  But computers have to approximate them with a limited number of bits, so they can only be so precise, and they can only get so large or small before the computer just calls them "infinity" or "zero".

This means that every numerical code is written with the assumption that the numbers you give it will fall within a certain range.  Once you go outside that range, its assumptions start failing and the results become meaningless.

**Comment by isjoung** [comment] 2016-05-02 23:01
How about this?
```python

#!/usr/bin/env python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
import cPickle
import parmed as pmd

platform_name = 'CPU'
#platform_name = 'CUDA'

with open('input.dat','rb') as f:
    system, prmtop, inpcrd = cPickle.load(f)

system.removeForce(0)
system.removeForce(0)
system.removeForce(0)
prmtop.DFIRE_FORCE_GROUP = 13

integrator = mm.LangevinIntegrator(300.0*unit.kelvin, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)
platform = mm.Platform.getPlatformByName(platform_name)
simulation = app.Simulation(prmtop.topology, system, integrator, platform)
context = simulation.context
context.setPositions(inpcrd.positions)

dene_dict = pmd.openmm.energy_decomposition(prmtop, context)
print( dene_dict )
```

CPU:
{'total': 56336477941216.68, 'nonbonded': 56336477937418.9, 'dfire': 3797.767595666509, 'bond': 0.0}

CUDA:
{'total': -6.71629646532508e+36, 'nonbonded': 56336477937205.7, 'dfire': -6.71629646532508e+36, 'bond': 0.0}

**Comment by isjoung** [comment] 2016-05-03 00:03
I also tried to remove one more `Force` then I get

CPU:
{'total': 3797.767595666509, 'dfire': 3797.767595666509, 'bond': 0.0}

CUDA:
{'total': 3797.714389047698, 'dfire': 3797.714389047698, 'bond': 0.0}

Removing one more,

CPU:
{'total': 3797.767595666509, 'dfire': 3797.767595666509}

CUDA:
{'total': 3797.714389047698, 'dfire': 3797.714389047698}

-1e-36 is probably related to some kind of overflow. It is still odd that other energy components affect the energy value.

Important thing is this. I understand that accurate energy evaluation with this extremely messy coordinates is meaningless, but it should not give a number like -1e-36. As I said, I got the coordinates by energy minimization. If very high energy state suddenly changes to very low energy state, essentially energy minimization (or refining conformations) is impossible whatever method you may use.

**Comment by swails** [comment] 2016-05-03 00:13
If you switch to using double precision in CUDA, what happens?

**Comment by isjoung** [comment] 2016-05-03 00:20
`{'CudaPrecision': 'double'}` produces a similar result:
{'total': -6.71629646532508e+36, 'nonbonded': 56336512877523.91, 'dfire': -6.71629646532508e+36, 'bond': 0.0}

**Comment by peastman** [comment] 2016-05-03 17:46
I'm trying to load your .dat file, but pickle is failing with this error:

```
AttributeError: Can't get attribute 'file' on <module 'builtins' (built-in)>
```

I'm not sure what that means.  Perhaps you could send the original prmtop and inpcrd files, and use XmlSerializer to write the System to an XML file?

Until I can reproduce your results I'm just speculating, but I would guess you have two particles that are almost exactly on top of each other.  That would explain the huge nonbonded energy.  So how did you reach that state?  For that I have to speculate even more, but just as a guess, does your system include water?  Most water models do not include a Lennard-Jones term on the water hydrogens, instead relying on the oxygen's LJ repulsion to keep anything else from getting too close.  Personally, I think that's insane, but I didn't design the water models!  That means if a negatively charged atom gets too close to a water hydrogen, the attraction between them will grow without limit and the energy will go to negative infinity as they approach each other.  So you actually have to be really careful about how you do energy minimization to make sure it never gets close to one of those conformations.

**Comment by isjoung** [comment] 2016-05-04 00:58
There is no water model and I added a little bit of sigma and epsilon values on all the atoms if they are zero. Charges are turned off.

I attach serialized system, prmtop, and inpcrd files. There are five inpcrd files and the energies measured right after minimization are as follows.

```
#            total        angle         bond       chiral        dfire     dihedral    nonbonded
   1  -1.11938E+37  7.46793E+04  1.60498E+06  1.89468E+10 -1.11938E+37  3.04351E+03  3.51186E+09
   2  -1.34326E+37  7.11727E+04  2.43070E+06  6.50820E+08 -1.34326E+37  3.05982E+03  2.95045E+09
   3  -1.11938E+37  1.07664E+05  1.32771E+10  8.05697E+10 -1.11938E+37  3.02700E+03  3.45555E+13
   4  -8.95506E+36  9.98731E+04  4.48430E+10  2.26449E+10 -8.95506E+36  2.97302E+03  4.10945E+06
   5  -1.11938E+37  9.70259E+04  3.74165E+08  1.04396E+11 -1.11938E+37  2.94289E+03  6.76796E+08
```

Since inpcrds do not contain full digits, the energy may slightly different if they are recalculated with the coordinates. Some terms can be nan. My problem is the extremely low total energies which probably caused by the incorrect 'dfire' energies. With 'CPU', this never happened. With CPU, dfire energies are a few thousands (I presume that they are the correct numbers), so the total energy is fairly high. This is what I want to get. So it is not an issue whether other energy terms are high or low. There is no singular point in dfire energy landscape and each dfire bond energy ranges from -10 to ~50. Therefore, the summed energy cannot be -1e36.

With CPU platform, my energy minimization algorithm is working ok although I am currently challenged by another issue (#1477). But with CUDA platform, it does not work because it gives low energies on conformations which should have high energies.

[input.tar.gz](https://github.com/pandegroup/openmm/files/247993/input.tar.gz)

**Comment by peastman** [comment] 2016-05-04 17:28
Your input files have very severe clashes.  I wrote the following script:

```Python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

system = XmlSerializer.deserialize(open('system.xml').read())
inpcrd = AmberInpcrdFile('b001.inpcrd')
integrator = VerletIntegrator(0.001*nanosecond)
platform = Platform.getPlatformByName('OpenCL')
context = Context(system, integrator, platform)
context.setPositions(inpcrd.positions)
for force in system.getForces():
    group = force.getForceGroup()
    print(group, force.__class__.__name__, context.getState(getEnergy=True, groups={group}).getPotentialEnergy())
```

And here's the output:

```
0 HarmonicBondForce 6715254.698185981 kJ/mol
1 HarmonicAngleForce 312458.05020814866 kJ/mol
2 PeriodicTorsionForce 12734.052491228174 kJ/mol
11 NonbondedForce 14693613864.734463 kJ/mol
0 CMMotionRemover 6715254.698185981 kJ/mol
13 CustomCompoundBondForce 29535.91536063701 kJ/mol
```

Using CPU platform instead gives nearly identical results.  As you can see, the NonbondedForce has an absurdly high energy, while the CustomCompoundBondForce is fine.  Checking distances between atoms, there are a bunch of pairs that are less than half an angstrom apart.  That leads to the enormous energy.

I then added the following line immediately after the call to `setPositions()`:

```Python
LocalEnergyMinimizer.minimize(context)
```

Very often, that fails with this error:

```
Exception: Particle coordinate is nan
```

The forces are just too enormous for that platform to be able to deal with, and the numbers are blowing up.  The CUDA and OpenCL platforms are especially susceptible to that, because they store forces in 64 bit fixed point format, so they simply can't represent any force component larger than about 2 billion.  But it doesn't always fail.  (Energy minimization is not deterministic.)  Sometimes it succeeds and gives reasonable energies for everything:

```
0 HarmonicBondForce 1706.0800889321415 kJ/mol
1 HarmonicAngleForce 3546.7375845550073 kJ/mol
2 PeriodicTorsionForce 4251.8762669513835 kJ/mol
11 NonbondedForce -465.6923445037837 kJ/mol
0 CMMotionRemover 1706.0800889321415 kJ/mol
13 CustomCompoundBondForce 16084.707307161065 kJ/mol
```

I also tried the CPU platform, and it never had any problem.  So I'd recommend using the CPU platform to do the energy minimization.  You can then save the minimized coordinates, and use those as the starting point for the actual simulation, which you do with the CUDA platform.

**Comment by isjoung** [comment] 2016-05-05 09:05
After rebooting my GPU card, interestingly the extreme negative number has gone. However, it is still a concern that the first example gives weird energies.

This is 'CUDA' result.

Without removing any force 
{'angle': 104374.10686638913, 'dfire': nan, 'nonbonded': 56336477937205.836, 'bond': 26636612264.855366, 'total': nan, 'dihedral': nan}

removing one term
{'angle': 104374.10686638913, 'dfire': nan, 'nonbonded': 56336477937205.82, 'bond': 0.0, 'total': nan, 'dihedral': nan}

removing two terms
{'dfire': nan, 'total': nan, 'nonbonded': 56336477937205.7, 'dihedral': nan, 'bond': 0.0}

removing three terms
{'total': nan, 'nonbonded': 56336477937205.72, 'dfire': nan, 'bond': 0.0}

removing four terms
{'total': 3797.714389047698, 'dfire': 3797.714389047698, 'bond': 0.0}

removing five terms
{'total': 3797.714389047698, 'dfire': 3797.714389047698}

As you see, the difference before and after rebooting is in 'dfire' term. I don't know why previously the number was -1e36 but now it is nan. For now, unfortunately I cannot reproduce the previous behaviour. Also, rigorous search of conformation cannot find the extremely negative energy traps. The saved coordinates now gives just nan, which is fine to me.

It is still odd that the 'dfire' term gives correct number after removing several terms. I hope this weird energy decomposition only happens when the total energy is extremely high (near precision limit). If this is true, my problem is resolved.

**Comment by peastman** [comment] 2016-05-05 16:18
Did you see my previous message?  I already explained what's going on.

**Comment by isjoung** [comment] 2016-05-05 17:53
> The forces are just too enormous for that platform to be able to deal with, and the numbers are blowing up. The CUDA and OpenCL platforms are especially susceptible to that, because they store forces in 64 bit fixed point format, so they simply can't represent any force component larger than about 2 billion. But it doesn't always fail. (Energy minimization is not deterministic.) Sometimes it succeeds and gives reasonable energies for everything:

Oh, I thought it affects only the total energy. I guess you meant that it also breaks individual energy terms which are parts of the sum. Thank you for the clarification.

**Comment by peastman** [comment] 2016-05-05 17:59
The problem is that it blows up and your coordinates turn into nan.  At that point, anything you try to calculate will produce something meaningless.  But the problem which caused it to blow up in the first place was the huge nonbonded forces, and the fact that they exceeded the range of the numeric representation being used.

Once you minimize it with the CPU platform, all the forces are very reasonable.  So then you can simulate it with any platform.

**Comment by isjoung** [comment] 2016-05-18 12:19
I am sorry that I have to come back to this issue again. I tried several things and found CUDA platform sometimes gives 'nan' and sometimes gives huge negative numbers (eg. -1.e38 - -1e13). It is uncontrollable. At the beginning I simply gave up conformations below a certain number but later I found that the negative number varies wide. So this temporal filtering method does not work either. The fact that it happens even when all the energy terms are finite make me suspect that there is other underlying problem. I saved the problematic coordinates and tested further to isolate the actual bond that gives the nonsensical energy. First, the system is serialized and removed the compoundbonds gradually until I get a reasonable number.

Finally I could reduce the number of compound bonds and prepared three serialized systems: system.xml, system2.xml, and system3.xml. The first one includes all the compond bonds (271 bonds), the second one includes the first half of the compound bonds (136 bonds) and the last one includes the last half of the compound bonds (135 bonds). For the three systems, I tested with the following code:

```python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *
import numpy as np

xmlfile = 'system.xml'

# CUDA
system = XmlSerializer.deserialize(open(xmlfile).read())
inpcrd = AmberInpcrdFile('b012.inpcrd')
integrator = VerletIntegrator(0.001*nanosecond)
platform = Platform.getPlatformByName('CUDA')
context = Context(system, integrator, platform)
context.setPositions(inpcrd.positions)
print 'CUDA energy'
for force in system.getForces():
    group = force.getForceGroup()
    print(group, force.__class__.__name__, context.getState(getEnergy=True,groups={group}).getPotentialEnergy())
frc_cuda = np.array( context.getState(getForces=True).getForces().value_in_unit(kilojoule_per_mole / nanometer) )

# CPU
system = XmlSerializer.deserialize(open(xmlfile).read())
inpcrd = AmberInpcrdFile('b012.inpcrd')
integrator = VerletIntegrator(0.001*nanosecond)
platform = Platform.getPlatformByName('CPU')
context = Context(system, integrator, platform)
context.setPositions(inpcrd.positions)
print 'CPU energy'
for force in system.getForces():
    group = force.getForceGroup()
    print(group, force.__class__.__name__, context.getState(getEnergy=True,groups={group}).getPotentialEnergy())
frc_cpu = np.array( context.getState(getForces=True).getForces().value_in_unit(kilojoule_per_mole / nanometer) )

# nan check
print 'CUDA force NAN', np.any(np.isnan(frc_cuda))
print 'CPU force NAN', np.any(np.isnan(frc_cpu))

# huge force check
print 'CUDA huge force', np.any(np.absolute(frc_cuda) > 1.e20)
print 'CPU huge force', np.any(np.absolute(frc_cpu) > 1.e20)
```

system.xml
```
CUDA energy
(0, 'HarmonicBondForce', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.00567724317, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.1131374199, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797864458.705, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=-1.2762655537073804e+38, unit=kilojoule/mole))
CPU energy
(0, 'HarmonicBondForce', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.0082119352, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.114320179244, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797908565.8386, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=49.08476853426457, unit=kilojoule/mole))
CUDA force NAN False
CPU force NAN False
CUDA huge force False
CPU huge force False
```
The compoundbond energy term is -1e38 for CUDA and 49.08 for CPU. As I said, -1e38 sometimes changes to 'nan'. Interestingly, all the atomic forces are finite (less than 1e20).

system2.xml
```
CUDA energy
(0, 'HarmonicBondForce', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.00567724317, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.1131374199, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797864459.4424, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=49.24361482448876, unit=kilojoule/mole))
CPU energy
(0, 'HarmonicBondForce', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.0082119352, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.114320179244, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797908565.8386, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=49.45769770482798, unit=kilojoule/mole))
CUDA force NAN False
CPU force NAN False
CUDA huge force False
CPU huge force False
```

system3.xml
```
CUDA energy
(0, 'HarmonicBondForce', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.00567724317, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.1131374199, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797864455.2886, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901078.9359635548, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=-0.3729309253394604, unit=kilojoule/mole))
CPU energy
(0, 'HarmonicBondForce', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(1, 'HarmonicAngleForce', Quantity(value=438571.0082119352, unit=kilojoule/mole))
(2, 'PeriodicTorsionForce', Quantity(value=34426.114320179244, unit=kilojoule/mole))
(11, 'NonbondedForce', Quantity(value=1537797908565.84, unit=kilojoule/mole))
(0, 'CMMotionRemover', Quantity(value=1901079.0271332858, unit=kilojoule/mole))
(13, 'CustomTorsionForce', Quantity(value=0.0, unit=kilojoule/mole))
(14, 'CustomCompoundBondForce', Quantity(value=-0.3729291705634096, unit=kilojoule/mole))
CUDA force NAN False
CPU force NAN False
CUDA huge force False
CPU huge force False
```
For system2 and system3, CUDA and CPU energies are similar and there seem to be no problem in calculating energy.

Therefore, it is can be concluded that the 'nan' error is system size dependent. Note that I didn't change other energy terms for the three systems. So, we cannot say that the 'nan' error is caused by other energy terms. I used TitanX and I think that GPU memory is enough.

Test files are attached. 
[compoundbond.tar.gz](https://github.com/pandegroup/openmm/files/270450/compoundbond.tar.gz)

**Comment by peastman** [comment] 2016-05-19 20:45
I found the problem.  It was an edge case - literally.  When you create a tabulated function, you specify a range for the table.  Whenever an argument is outside that range, the function is zero.  But in this case, the distance between two particles just happened to *exactly* equal the upper limit of the range.  That led to incorrect indexing and reading coefficients from the wrong memory location.

This error only affected continuous 2D and 3D functions, and only on the CUDA and OpenCL platforms.  1D functions worked correctly on all platforms.

I'll have a PR with the fix coming shortly.

**Comment by peastman** [comment] 2016-05-19 20:54
The fix is in #1495.  Thanks for the excellent test case!

**Comment by isjoung** [comment] 2016-05-20 07:58
The fix works! I tested some other coordinates and also tried energy minimization with diverse conformations. I don't see spikes in the compound bond energy term anymore. Thank you!

**Comment by peastman** [comment] 2016-05-20 15:55
Great!  I just merged the fix.

**Closed** 2016-05-20 15:55 UTC
