### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#216] opened 2013-11-08 21:15 UTC
This was brought up by Vijay/John earlier. Is it possible have resumable state xmls that are deterministic and reproducible (across different types of GPUs, and possibly, across different platforms?). Currently, even Context->save/loadCheckpoint isn't entirely deterministic due to atomics in PME (though we can change this).

**Comment by peastman** [comment] 2015-06-26 00:04
I'm closing this, since checkpoints serve this function.  They aren't portable across different types of GPUs, but it's impossible to get both portability *and* exact reproducibility.  So we offer two different mechanisms to choose from: checkpoints give exact reproducibility, and states give portability.

**Closed by peastman** 2015-06-26 00:04 UTC
