### ISSUE TITLE
Update benchmarks?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1576] opened 2016-09-02 12:50 UTC
Does anyone have the ability to provide more up-to-date benchmarks for OpenMM 7.0.1 on recent hardware, like the GTX-1080, GTX-1070, GTX-TITAN-X Pascal, K40, or K80?

The current benchmarks page is pretty stale:
http://openmm.org/about.html#benchmarks

In fact, there's almost no overlap with the AMBER GPU benchmarks page anymore, which is pretty good about staying current with available hardware:
http://ambermd.org/gpus/benchmarks.htm#Benchmarks

**Comment by yudongqiu** [comment] 2016-09-03 06:24
We recently performed some benchmarks on our newly-built workstation with the EVGA GTX 1080 FTW and Titan X Pascal. OpenMM was cloned from github repository master branch just now so I suppose that's the latest version. I have attached the outputs of the examples/benchmark.py and hopefully it will help.
[OpenMM_Benchmark_TitanX_Pascal.txt](https://github.com/pandegroup/openmm/files/453227/OpenMM_Benchmark_TitanX_Pascal.txt)
[OpenMM_Benckmark_GTX_1080_FTW.txt](https://github.com/pandegroup/openmm/files/453226/OpenMM_Benckmark_GTX_1080_FTW.txt)

**Comment by jchodera** [comment] 2016-09-04 23:21
Thanks! Any chance you would be able to rerun these in `mixed` precision mode?

**Comment by yudongqiu** [comment] 2016-09-05 00:48
Sure. I will run them and report the output soon. Meanwhile, I would like to address that the Titan X Pascal benchmark results seems to be affected by its thermal conditions. I noticed that it slows down after running the benchmark several times. Here is another Titan X benchmark result in single precision from the first time I ran it today:
[OpenMM_Benchmark_TitanX_Pascal_best.txt](https://github.com/pandegroup/openmm/files/454204/OpenMM_Benchmark_TitanX_Pascal_best.txt)

The PME speed increased quite a bit, and polarizable models is not affected since it's not bottlenecked by the GPU computing power.

**Comment by yudongqiu** [comment] 2016-09-05 01:23
Here are the benchmark results in `mixed` precision.
[OpenMM_Benchmark_TitanX_Pascal_Mixed.txt](https://github.com/pandegroup/openmm/files/454222/OpenMM_Benchmark_TitanX_Pascal_Mixed.txt)
[OpenMM_Benckmark_GTX_1080_FTW_Mixed.txt](https://github.com/pandegroup/openmm/files/454223/OpenMM_Benckmark_GTX_1080_FTW_Mixed.txt)

**Comment by jchodera** [comment] 2016-09-06 00:51
Thanks, @yudongqiu!

**Comment by jchodera** [comment] 2016-09-06 01:04
@peastman: These numbers are interesting. For a GTX-1080, going from `single` to `mixed` has minimal impact for the slower methods (`pme`, `amoeba*`) as would be expected, but can significantly impact faster nonbonded methods (789 to 684 ns/day for `gbsa` for a 13% slowdown; 572 to 485 ns/day for `rf` for a 15% slowdown). These numbers are consistent with a difference of only 54 us/step in going from `single` to `mixed` precision for the integrator. It seems like it would be difficult, but I wonder if there's any way to shave off some of that time.

**Comment by giadefa** [comment] 2016-09-06 08:12
I am trying to run the benchmarks, but I get this:

[gianni@suo examples]$ python benchmark.py --test=pme --platform=CUDA
 --precision=mixed
Platform: CUDA
Precision: mixed

Test: pme (cutoff=0.9)
Step Size: 2 fs
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    runOneTest(options.test, options)
  File "benchmark.py", line 95, in runOneTest
    context = mm.Context(system, integ, platform, properties)
  File "/shared/gianni/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py",
line 13878, in __init__
    this = _openmm.new_Context(*args)
Exception: Illegal property name: Precision


What am I doing wrong?
Using openmm from omnia:
openmm                    7.0.1                    py35_0    omnia

and cuda7.5

gianni

**Comment by jchodera** [comment] 2016-09-06 08:20
I think this is because you are trying to run benchmark.py from the latest
source snapshot but have OpenMM 7.0.1 or earlier installed. If you want to
profile 7.0.1 or earlier, grab examples/benchmark.py from the 7.0.1 release
source and you should be good.

The error is due to a change in the way precision can be specified in the
development version: OpenMM now supports "Precision" in addition to
"CudaPrecision" and "OpenCLPrecision", but the older versions did not
support this---hence the error.

**Comment by giadefa** [comment] 2016-09-06 08:36
Thanks John. Indeed I was doing that.

From benchmark.py of release 7.0.1 I now get this:

[gianni@suo examples]$ python benchmark.py --test pme --platform CUDA
 --precision mixed
Platform: CUDA
Precision: mixed

Test: pme (cutoff=0.9)
Step Size: 2 fs
Traceback (most recent call last):
  File "benchmark.py", line 151, in <module>
    runOneTest(options.test, options)
  File "benchmark.py", line 101, in runOneTest
    context = mm.Context(system, integ, platform, properties)
  File
"/shared/gianni/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py",
line 13878, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 32512
sh: /usr/local/cuda/bin/nvcc: No such file or directory

[gianni@suo examples]$ which nvcc
/shared/lab/software/cuda/7.5/bin/nvcc

So nvcc is available but do I need it in a specific location?

What about Cuda8.0 and Pascal? If I run on Cuda8 it does not recognize the
CUDA platform as available.


gianni

**Comment by jchodera** [comment] 2016-09-06 14:34
For CUDA 7.5, you can specify a nonstandard CUDA install path by:
* Setting the `OPENMM_CUDA_COMPILER` environment variable to point to your `nvcc`
* Adding `$CUDA_HOME/lib64` to your `LD_LIBRARY_PATH` environment variable

I fully admit the autodetection of CUDA install locations could be improved!

Currently, I believe only CUDA 7.5 is supported by the conda-installable `openmm` package (is that right @peastman?), but it would be great if we could build packages for more recent CUDA versions as well. I bet we could build different versions with different `cuda75` and `cuda80` labels or using the [feature tracking capability](http://conda.pydata.org/docs/building/meta-yaml.html#features).

**Comment by peastman** [comment] 2016-09-06 15:41
It's going to be hard to do much about that.  The GTX 1080 has terrible double precision performance (I think maybe a 32:1 ratio of single:double flops?), so that's what we're trying to work around.  The best approach is to avoid using double, and mixed precision is already pretty selective about where it uses it.

**Comment by peastman** [comment] 2016-09-06 17:34
Actually, I see why GB is affected so much.  For standard nonbonded forces it compiles multiple versions of the kernel, depending on whether it needs energy or not.  But for the GB kernel it always computes energy whether it's needed or not.  And since mixed precision mode does energy accumulation in double precision, that kernel gets slowed down.

For RF, it's mostly from applying the constraints.  That has to be done in double precision, which makes it a lot slower.  The SETTLE kernel takes about 8 times as long, and the SHAKE kernel takes about 5 times as long.

**Comment by mj-harvey** [comment] 2016-09-06 20:02
@yudongqiu

I'm not able to reproduce your performance figures- could you post more details about your system configuration?

For reference:

$ uname -a
Linux xxx 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(Centos 7.2)

$ cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.44  Wed Aug 17 22:24:07 PDT 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26

(Comparable performance observed with 7.5)

$  python ./benchmark.py --platform=CUDA --device=1 --pme-cutoff=0.9 --precision=single  --test=pme --seconds=360 Platform: CUDA
Precision: single
Device: 1

Test: pme (cutoff=0.9)
Step Size: 2 fs


Over the run the GPU reaches a steady-state  of 82C, 54% fan  120/180W, 89% load (reported by nvidia-smi)

My GTX1080 is stock, the FTW version is approx 7% faster. If you are seeing a higher GPU utilisation, that could account for the difference.

**Comment by peastman** [comment] 2016-09-06 20:33
You quoted the output of the benchmark script up to just before it printed the results, but then you left those off?

**Comment by mj-harvey** [comment] 2016-09-06 20:40
@peastman  fixed

**Comment by peastman** [comment] 2016-09-06 20:46
Thanks!  Which version of the code was that run with?  7.0.1 or the latest development code?

**Comment by mj-harvey** [comment] 2016-09-06 20:47
That's commit 73c4302d9424251a3820bcfacb3a68c6d66124c9 , the head of master as of a few hours ago.

**Comment by giadefa** [comment] 2016-09-06 21:59
What's the right thing to benchmark, single or mixed precision? I mean is
single usable in production?

**Comment by giadefa** [comment] 2016-09-06 21:59
Matt, try on the Titan X as well, that's for use the same hardware.

g

**Comment by peastman** [comment] 2016-09-06 22:08
It depends on exactly what you're simulating and what you want to learn from it, but here's a good guideline.  For constant temperature simulations, single precision is usually fine.  For constant energy simulations, you probably want mixed precision.

If the performance is slower than you expect, you might also try deleting the cached kernels (in `/tmp` or whatever is set as your temp directory).  OpenMM can compile kernels with either the standalone `nvcc` compiler or the runtime compiler library, but it turns out that the runtime compiler produces slower code than `nvcc`.  (I'm told that will be fixed in the release version of CUDA 8.)  So I just recently modified it to prefer `nvcc` over the runtime compiler when they're both available.  But perhaps you have some cached kernels still in your temp directory.

**Comment by giadefa** [comment] 2016-09-06 22:18
but single is totally single? How do you do shake/Settle with just single
precision?

**Comment by peastman** [comment] 2016-09-06 22:28
By calculating them in single precision. :)  You have to be a bit careful in how you do it.  For example, you need to apply the constraints directly to the displacements from the previous time step *before* you add them to the positions.  Also, we frequently re-image the molecules to keep everything in a single periodic box, so the coordinates never get too large.  But if you do those things, precision isn't usually an issue.  It's rare to specify a constraint tolerance smaller than about 1e-6, and that's easily achievable in single precision.

**Comment by yudongqiu** [comment] 2016-09-06 22:58
@mj-harvey 
```
$ git log: 
commit 73c4302d9424251a3820bcfacb3a68c6d66124c9
$ uname -a: 
Linux lpwstation 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/driver/nvidia/version:
NVRM version: NVIDIA UNIX x86_64 Kernel Module  370.23  Mon Aug  8 18:02:36 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26
$ python ./benchmark.py --platform=CUDA --device=1 --pme-cutoff=0.9 --precision=single --test=pme --seconds=360
Platform: CUDA
Precision: single
Device: 1

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 677648 steps in 355.135 seconds
329.727 ns/day
```
During the run our 1080 FTW reached 78C, 175W / 215W, 94% utilization from nvidia-smi.
I also noticed that the GPU clock was running at (4513, 1959) MHz for the Memory and Graphics, even after I manually set the application clocks to be (5005, 2025) MHz at the maximum supported level.

**Comment by giadefa** [comment] 2016-09-07 02:48
ok. I think to remember that we had issues with all single precision with
acemd and never used it, but I don't remember the issues anymore. Maybe it
was reasonable energy conservation but I am not sure. Even if you are in
NVT, you still want to have minimal intervention of the thermostat.

**Comment by yudongqiu** [comment] 2016-09-19 18:11
I just got an updated on the benchmark results. After applying recent updates #1582 #1583 , the amoebapme test is now running a lot faster. (~15 ns/day in single precision with Titan X Pascal)
[OpenMM_Benchmark_TitanX_Pascal.txt](https://github.com/pandegroup/openmm/files/480754/OpenMM_Benchmark_TitanX_Pascal.txt)
[OpenMM_Benchmark_TitanX_Pascal_mixed.txt](https://github.com/pandegroup/openmm/files/480774/OpenMM_Benchmark_TitanX_Pascal_mixed.txt)

**Comment by giadefa** [comment] 2016-09-20 15:38
With the help of John we could confirm the benchmarks here on a Titan X
Pascal.
A couple of comments.
1) The collision in the langevin thermostat is unreasonably high in the
benchmark.py. I think 91 ps^-1. This is probably a typing error because it
should be 0.1 or less than 1. This high value produces a huge friction and
slow diffusion, atoms do not move so much and the benchmark is around
20ns/day higher than with a normal number.
2) One reason why we could not reproduce the benchmark figures was due to
using Charmm and switching functions. How does the Amber DHFR copes without
switching for non zero force at the cutoff and why switching is so slow?

Gianni

**Comment by peastman** [comment] 2016-09-20 17:55
The implicit solvent benchmarks use 91 because that's the actual friction coefficient of water.  Of course, if you're mainly interested in conformational exploration you might choose to use a smaller value.  But if you want the implicit solvent to reproduce all aspects of water as well as possible, including its friction, 91 is the right value to use.

For explicit solvent you wouldn't use that large a value because you already have water molecules providing friction.  I think the benchmark uses 1 in that case.

NonbondedForce has a built in switching function that adds very little overhead.  To use it, just call `setUseSwitchingFunction()` and `setSwitchingDistance()`.  I think CHARMM may instead use a CustomNonbondedForce to implement their own switching function, but I can't tell you the details.

**Comment by giadefa** [comment] 2016-09-20 18:38
For the friction this is set to 91 if you use PME as well at line 80 of
benchmark.py if I read it well

integ = mm.LangevinIntegrator(300*unit.kelvin, 91*(1/unit.picoseconds), dt)

It does matter in the context of the benchmark because the benchmark
numbers change by changing that.

**Comment by peastman** [comment] 2016-09-22 23:14
You're right - oops!  I just sent a PR fixing it.  But it has negligible effect on the benchmark numbers.  The friction coefficient doesn't change either the step size or the cost of computing a time step.

**Comment by giadefa** [comment] 2016-09-22 23:21
OK. It was just 20 ns/day less going from 91 to 0.1. I assumed that there
was a cost due to higher diffusion made recomputing pairlists  more
frequently or something.

**Comment by peastman** [comment] 2016-09-23 00:27
I just ran some tests of this.  With the standard PME benchmark running on a GTX 980, changing the friction from 91 to 1 changes the speed from 140.0 to 138.2 ns/day, or about a 1% change.  With heavy hydrogens and a larger time step, the difference is a little bigger: from 290 to 280 ns/day, or about a 3% difference.  That's probably because it needs more iterations for the constraints.

**Comment by zonca** [comment] 2016-11-29 01:14
I'm testing on a P100, can somebody please share a script to run the same exact 6 configurations in http://openmm.org/about.html#benchmarks?

**Comment by jchodera** [comment] 2016-11-29 03:25
@zonca: Clone the `openmm` repository and run the `examples/benchmark.py` script. I think this should do it:
```bash
git clone https://github.com/pandegroup/openmm.git
cd openmm/examples/
python benchmark.py --platform=CUDA --test=gbsa
python benchmark.py --platform=CUDA --test=gbsa --heavy-hydrogens
python benchmark.py --platform=CUDA --test=rf
python benchmark.py --platform=CUDA --test=rf --heavy-hydrogens
python benchmark.py --platform=CUDA --test=pme
python benchmark.py --platform=CUDA --test=pme --heavy-hydrogens
```
Replace `CUDA` with `OpenCL` if you want to benchmark OpenCL performance.

Could you report which version you benchmarked and the results here?

**Comment by zonca** [comment] 2016-11-29 03:50
thanks @jchodera do you also have the settings for CPU? just to crosscheck

**Comment by jchodera** [comment] 2016-11-29 04:00
Replace `CUDA` with `CPU` in the above example to use the OpenMM multithreaded CPU platform. It will automatically detect the number of cores available.

**Comment by zonca** [comment] 2016-11-29 04:12
@jchodera I read somewhere that for CPU the cutoff was different, is it still the case?

**Comment by jchodera** [comment] 2016-11-29 04:17
Performance can be quite dependent on cutoff (and on other parameters like Ewald error tolerance). You might try a few cutoffs with the `--pme-cutoff=CUTOFF` option, where the default is 0.9 (nanometers).

**Comment by peastman** [comment] 2016-11-29 17:08
The CPU PME benchmarks set the cutoff to 0.8.  All the details are at https://simtk.org/plugins/moinmoin/openmm/BenchmarkOpenMMDHFR.

**Comment by zonca** [comment] 2016-11-30 15:13
thanks @peastman , wouldn't it be useful to have a `run_benchmark.sh` script in the repo that runs those 6 configurations for each of the available platforms?

**Comment by zonca** [comment] 2016-11-30 17:36
@jchodera here my results for P100 and K80:

```
                        CUDA (Tesla P100)  CUDA (Tesla K80)
Simulation Type                                            
Implicit, 2 fs                        617               247
Implicit, 5 fs HMR                    941               448
Explicit-RF, 2 fs                     461               157
Explicit-RF, 5 fs HMR                 748               307
Explicit-PME, 2 fs                    268               103
Explicit-PME, 5 fs HMR                558               208
```

see also `.csv`: https://gist.github.com/zonca/33da6212cf2c2d8400e9254c175c96d7

**Comment by jchodera** [comment] 2016-11-30 19:13
Thanks, @zonca!

I totally agree it would be great to have a benchmarking script in the OpenMM repo, as well as a lot more organization to that `examples/` directory.

**Comment by jchodera** [comment] 2016-12-06 03:16
> thanks @peastman , wouldn't it be useful to have a run_benchmark.sh script in the repo that runs those 6 configurations for each of the available platforms?

@peastman : What do you think about (1) organizing the `examples/` directory a bit, and (2) including the `run_benchmark.sh` and `benchmark.py` scripts in a separate `benchmark/` directory?

**Comment by jchodera** [comment] 2016-12-24 06:06
> @peastman : What do you think about (1) organizing the examples/ directory a bit, and (2) including the run_benchmark.sh and benchmark.py scripts in a separate benchmark/ directory?

Any thoughts on this? Now would be a good time to clean this up.

**Closed** 2017-04-10 02:07 UTC
