### ISSUE TITLE
NaN issues on OpenCL with PME and harmonic restraints

### ISSUE THREAD

**Issue by pschmidtke** [pandegroup/openmm#2111] opened 2018-07-05 20:11 UTC
Hi,

I'm trying to run an openmm simulation on my GTX 980 with CUDA Driver Version: 387.178 and CUDA  V8.0.61, openmm 7.1.1.dev-c1a64aa
using OpenCL. 
I attach the full workflow of protein preparation with pdbfixer, water parametrization, box set up, minimization, CPU based heating (working), OpenCL based heating (failing with NaN errors). I also write energy files and dcd files and as soon as OpenCL is used it appears that potential energies is extremely high (like if there were suddenly steric clashes etc). 
I tried : 
UseCpuPme true/false
DisablePmeStream true/false
-> no change

I also tried to lower the force constant on the harmonic restraints, this made things a bit more stable. 
Lower temperatures and smaller integration steps also influence the stability, but a bit less than the force constant. 

What explains the huge difference in behaviour between CPU / GPU here? Is it my set up? Is the PME box correctly considered recognized on GPU?

Any help is appreciated.

Code is attached.

[gpu_debug.zip](https://github.com/pandegroup/openmm/files/2168071/gpu_debug.zip)

**Comment by peastman** [comment] 2018-07-05 20:17
Could you try running this with OpenMM 7.2.2?  It may not make any difference, but as a first step in debugging the problem, it's good to verify you aren't running into a problem that's already been fixed in a later release.

**Comment by peastman** [comment] 2018-07-05 23:02
I think the problem is in the way you've defined the CustomExternalForce:

```python
force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
```

Since you're using periodic boundary conditions, the coordinates x, y, and z are only defined up to a translation by lattice vectors.  So instead you should define it like this:

```python
force = mm.CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
```

See the discussion of this issue in the API docs at http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html#simtk.openmm.openmm.CustomExternalForce.

**Comment by abradle** [comment] 2018-07-06 06:43
@peastman Thanks so much! that works for me!

**Comment by peastman** [comment] 2018-07-06 15:53
Great!

**Closed by peastman** 2018-07-06 15:53 UTC

**Comment by pschmidtke** [comment] 2018-07-06 21:23
Hey, thanks @peastman . Indeed that seems to fix the issue. 
In another script I have an expression like this one : 

pullforce = mm.CustomExternalForce('k_sp*0.5*(R-R0)^2; \
                                   R = sqrt((x-x0)^2+(y-y0)^2+(z-z0)^2);')

Replacing the distance R with the periodicdistance is sufficient here or do I also have to rewrite the (R-R0) part here?

**Comment by peastman** [comment] 2018-07-06 21:32
That should be fine.

**Comment by pschmidtke** [comment] 2018-07-07 13:37
I'm hijacking the post here! :)

Is there any way to rewrap water around the protein (so to keep original protein coordinates, but wrap solvent box around it after solvation with pdbfixer?)

**Comment by peastman** [comment] 2018-07-07 14:51
I'm not sure what you mean by rewrapping the water?

**Comment by jchodera** [comment] 2018-07-13 14:54
> Is there any way to rewrap water around the protein (so to keep original protein coordinates, but wrap solvent box around it after solvation with pdbfixer?)

I think you might be able to use MDTraj for that. Check out [`image_molecule`](http://mdtraj.org/1.9.0/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules)

**Comment by pschmidtke** [comment] 2018-07-13 17:11
OK will try that out. Hopefully it won't mess with my Smirnoff parmed chameleon topology ;) will test in two weeks

Cheers

Sent from BlueMail<http://www.bluemail.me/r?b=13130>
On Jul 13, 2018, at 16:54, John Chodera <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there any way to rewrap water around the protein (so to keep original protein coordinates, but wrap solvent box around it after solvation with pdbfixer?)

I think you might be able to use MDTraj for that. Check out image_molecules<http://mdtraj.org/1.9.0/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules>.
