### ISSUE TITLE
Possible bug with CustomIntegrator, OpenCL, and Force Groups

### ISSUE THREAD

**Issue by scons** [pandegroup/openmm#1815] opened 2017-05-18 17:20 UTC
Hi All,

I'm trying to implement force field mixing in OpenMM.  My approach was to use the CustomIntegrator class.  I load up an MD simulation with two difference force fields and add them to two difference force groups.  The, during integration, I use 'energy1' and 'energy2' to compute a weighting factor, and then create an 'fmix' that is a linear combination of 'f1' and 'f2' based on the weighting factors.  I have been testing my code and have noticed very strange behavior but only when using OpenCL.  The Reference and CPU platforms give a reasonable output in terms of the potential energy (energy1 + energy2) and the temperature.  However, upon selecting the OpenCL platform it seems that something is happening to the energy which drives the temperature higher and higher. Scaling down dt by a factor of 10 does not help the problem, it simply slows it down.  

Attached are potential energy and temperature as a function of step count for CPU platform and OpenCL platform on identical systems, and a code snippet for my custom integrator.  The only difference in the two runs was switching between the CPU or OpenCL platform.

Thank you for any and all advice.

[CPU.txt](https://github.com/pandegroup/openmm/files/1011730/CPU.txt)
[OpenCL.txt](https://github.com/pandegroup/openmm/files/1011731/OpenCL.txt)
kB = 6.0221367e23\*1.380658e-23/1000.0
dt = 0.00025\*picoseconds
#...
integrator = CustomIntegrator(dt)
integrator.addGlobalVariable("kT", kB\*50.0) #temperature multiplied by kB
integrator.addGlobalVariable("g", 1.0) #gamma, aka friction
integrator.addGlobalVariable("bmix", 0.06) #beta mix, a free parameter

integrator.addGlobalVariable("vscale", 0)
integrator.addGlobalVariable("fscale", 0)
integrator.addGlobalVariable("noisescale", 0)
integrator.addGlobalVariable("normE", 0)
integrator.addGlobalVariable("expwt1", 0)
integrator.addGlobalVariable("expwt2", 0)
integrator.addGlobalVariable("expsum", 0)

integrator.addPerDofVariable("xp", 0)
integrator.addPerDofVariable("fmix", 0)

integrator.addComputeGlobal("vscale", "exp(-dt\*g)")
integrator.addComputeGlobal("fscale", "(1-vscale)/g")
integrator.addComputeGlobal("noisescale", "sqrt(kT\*(1-vscale\*vscale))")

integrator.addComputeGlobal("normE", "energy1")
integrator.addComputeGlobal("normE", "min(normE, energy2)")
integrator.addComputeGlobal("expwt1", "exp(-bmix\*(energy1-normE))")
integrator.addComputeGlobal("expwt2", "exp(-bmix\*(energy2-normE))")
integrator.addComputeGlobal("expsum", "expwt1+expwt2")

integrator.addUpdateContextState();

integrator.addComputePerDof("fmix", "f1\*expwt1/expsum")
integrator.addComputePerDof("fmix", "fmix+f2\*expwt2/expsum")
integrator.addComputePerDof("v", "vscale\*v+fscale\*fmix/m+noisescale\*sqrt(1/m)\*gaussian")
integrator.addComputePerDof("xp", "x+dt\*v")
integrator.addComputePerDof("v", "(xp-x)/dt")
integrator.addComputePerDof("x", "xp")
#...

**Comment by peastman** [comment] 2017-05-18 18:14
Is it possible for you to post all the files needed to reproduce this (complete script, input files)?  I can take a look and try to figure out what's going on.

**Comment by scons** [comment] 2017-05-18 19:07
Hi Peter.  I will attach the input files and complete source code here.  I had to rename to .txt to allow GitHub to upload the files.  Beware the code is very pre-release!

[active.top.txt](https://github.com/pandegroup/openmm/files/1012052/active.top.txt)
[inactive.gro.txt](https://github.com/pandegroup/openmm/files/1012054/inactive.gro.txt)
[inactive.top.txt](https://github.com/pandegroup/openmm/files/1012053/inactive.top.txt)
[test_run.py.txt](https://github.com/pandegroup/openmm/files/1012055/test_run.py.txt)

**Comment by peastman** [comment] 2017-05-22 22:54
Thanks!  I figured out what the problem is.  Now I'm trying to figure out a way of fixing it without hurting performance.

**Comment by peastman** [comment] 2017-05-24 20:54
I just sent a PR with the fix.  It now works correctly, but it's a lot slower than it needs to be.  Let me describe what's going on.  Consider the following lines:

```Python
integrator.addComputeGlobal("normE", "energy1")
integrator.addComputeGlobal("normE", "min(normE, energy2)")
integrator.addComputeGlobal("expwt1", "exp(-bmix*(energy1-normE))")
integrator.addComputeGlobal("expwt2", "exp(-bmix*(energy2-normE))")
...
integrator.addComputePerDof("fmix", "f1*expwt1/expsum")
integrator.addComputePerDof("fmix", "fmix+f2*expwt2/expsum")
```

Notice how it keeps alternating between force groups 1 and 2.  Here's what happens when it's executing that *with the CPU platform*.

- It gets to the first line and sees it needs the energy of force group 1, so it runs a force/energy computation for that group.
- It gets to the second line and sees it needs the energy of group 2.  It doesn't know that so it runs a force/energy computation for group 2.
- It gets to the third line and sees it needs the energy of group 1.  It computed that before, but it hasn't kept it around.  It only stores the force and energy of the most recent group it's dealt with.  So it has to run another force/energy computation.
- It gets to the fourth line and sees it needs the energy of group 2.  Once again, it hasn't kept that around.  It threw out that information when it computed force group 1.  So it needs yet another force/energy computation.

And so on.  In all it performs 6 force/energy computations even though it really only needs 2 (one for each group).  It *could* be made to store that information, though, and that would be a really useful optimization to implement.

The OpenCL and CUDA platforms are different.  Those platforms *do* try to keep around forces from previously computed groups.  Unfortunately, there was a bug in the way that optimization was implemented, which led to the behavior you were seeing.  I've now fixed that.

It could still be improved, though.  It only stores forces from previous groups, not energies, so it still does 4 force/energy computations when only 2 are required.  I'll try to improve that in the future.

In the mean time, you can easily modify your integrator to work around that problem.  Just save the forces and energies yourself, being sure you do everything you need with one force group before moving on to the next one:

```Python
integrator.addComputeGlobal('savedEnergy1', 'energy1')
integrator.addComputePerDof('savedForce1', 'f1')
integrator.addComputeGlobal('savedEnergy2', 'energy2')
integrator.addComputePerDof('savedForce2', 'f2')
```

Now you can use those saved values, and it won't run any more unnecessary calculations.

**Comment by jchodera** [comment] 2017-05-24 21:14
Good catch!

Would the CUDA and OpenCL bugs have only affected the case where multiple force groups were in use?

Also, does this rise to the level of wanting to folding it into a bugfix release? If not, should we compile a list of known issues somewhere?

**Comment by peastman** [comment] 2017-05-24 21:25
> Would the CUDA and OpenCL bugs have only affected the case where multiple force groups were in use?

Correct.  It only happens when you're repeatedly alternating between force groups.  You have to work with group A, then group B, then come back to group A again.  Also, you have to use the *forces* from group A when you come back to it.  Accessing the energy wouldn't cause any problem because it wasn't trying to store that.

And of course, you need to do all that *without* modifying the particle positions.  As soon as you do that, it throws out all its cached forces because it knows they're no longer valid.

**Closed** 2017-05-24 22:30 UTC

**Comment by peastman** [comment] 2017-05-26 17:36
Actually, what I said before about the optimization wasn't quite true.  As you've written the integrator, it really does require four force/energy evaluations per step.  That's because you have an `addUpdateContextState()` right in the middle.  That invalidates previously computed forces, since it can change positions.  For example, if you have a barostat in your system, that's when it gets applied.  Is there a good reason it needs to be at that point?  If you move the `addUpdateContextState()` to the beginning, before the first time you access energy, then it only requires two force/energy evaluations.

**Comment by peastman** [comment] 2017-05-26 18:59
I just sent a PR with the optimizations: #1826.

**Comment by scons** [comment] 2017-05-26 19:11
Thank you very much for your work, Peter.  This will be immeasurably helpful for me.  I have just emerged from my final exam cocoon and will begin testing these changes ASAP. Thank you!!
