### ISSUE TITLE
NaN issue

### ISSUE THREAD

**Issue by sroet** [pandegroup/openmm#1666] opened 2016-11-10 17:00 UTC
I tried running 25 ns md with the script from the attached zip ([opennm_nan.zip](https://github.com/pandegroup/openmm/files/583926/opennm_nan.zip)) on several frames from a gromacs md run (which have triclinic box vectors). However, a lot of runs (7 out of 9) stop because of ```Particle coordinate is nan```, while gromacs runs them just fine. 

This seems to happen at random times (ranging from 0.28 ns to 24.68 ns).

I checked the forces between using gromacs directly and using the gromacs forcefields in OpenMM, and the total force per atom matches pretty well between them.

I also tried running it with the Langevin integrator and with some changes that were suggested to me by @jchodera :
- Setting ```integrator.setConstraintTolerance``` to ```(1.0e-8)```.
- Using ```OpenCL```.
- Running with ```properties ={'CudaDisablePmeStream':'true'}```.

But all of these still generate a bunch of NaNs as seen in this table:
![table](https://cloud.githubusercontent.com/assets/19587267/20185625/140ef63a-a76d-11e6-9864-316234a4a2e4.png)

I'm running this on:
GPU: NVIDIA GTX Titan X (Maxwell)
Driver Version: 352.79
CUDA Version: 7.5.18
Openmm Version: 7.1.0.dev-04b1a06

Does someone has an idea what might be causing this?

**Comment by jchodera** [comment] 2016-11-10 17:03
I can reproduce nearly all of these (in the sense that I see a `nan` after several ns) on our GTX-TITAN-X Maxwell with CUDA 7.5, the `openmm-7.1.0` conda preview build in the `dev` channel, and driver version 367.48. The only one I haven't seen fail yet is CUDA without PME stream on.

**Comment by peastman** [comment] 2016-11-10 20:37
It's hard to guess.  It's clearly something stochastic, but I can't say much more than that.  You posted your script, but none of the other files needed to reproduce it.  Can you post those?

**Comment by sroet** [comment] 2016-11-10 20:53
Sure, here's the full zip:
[openmm_nan.zip](https://github.com/pandegroup/openmm/files/584414/openmm_nan.zip)

**Comment by peastman** [comment] 2016-11-10 21:48
Thanks.  I have it running now.  About 1.5 ns so far with no errors.  It looks like I may have to run overnight to see anything.  This could be very very slow to debug.

I modified your script to use a LangevinIntegrator instead of the custom VVVRIntegrator.  I don't know if the problem is related to that, but I want to see if I can reproduce the problem when doing everything in as standard a way as possible.

**Comment by jchodera** [comment] 2016-11-11 01:49
It's possible that LangevinIntegrator works fine but the VVVRIntegrator (a
CustomIntegrator) is somehow the source of the NaNs. Let us know what you
find!

**Comment by dwhswenson** [comment] 2016-11-11 12:18
We had also run it with the OpenMM built-in Langevin before we contacted @jchodera, and had the same problems. I don't think we've run in NVT yet, though. @sroet : Can you try that, to see if it is a problem with the barostat and some combination of our other parameters?

**Comment by sroet** [comment] 2016-11-11 12:43
@dwhswenson:  I will start a set of NVT runs right away. 

The table after running overnight looks like this:
![table](https://cloud.githubusercontent.com/assets/19587267/20215421/79a87fdc-a814-11e6-92b8-df61e3d78d82.png)

**Comment by sroet** [comment] 2016-11-11 13:02
Already saw the first NaN on the NVT runs (after .60 ns, starting from frame 926)

**Comment by peastman** [comment] 2016-11-11 19:10
I was able to reproduce it with LangevinIntegrator.  To try to get more information, I modified it to record the energy at every timestep.  Of course, that slowed it down a lot, so I ran it overnight.  And of course, this time the error didn't happen!  *Probably* that's just by chance.  Anyway, I've started it going again.

**Comment by peastman** [comment] 2016-11-14 21:26
I managed to get a trace of the energy as it blows up.  It happens gradually.  Starting about 30-40 time steps before the end, the potential energy starts to decrease and the kinetic energy starts to increase.  It's gradual at first, but then speeds up in the last 10 time steps, with the potential energy dropping by over 250 kJ/mol in just those 10 steps.  Then it completely blows up.

So the system is pretty clearly falling into some sort of a hole.  I suspect it's caused by a hydrogen atom with no LJ term on it.  I'm running a new simulation where I record the forces as well as energies, so I should be able to see from that exactly what's happening.  But that makes it run *much* slower (about 2 ns/day), so it could take a while to get results.

**Comment by jchodera** [comment] 2016-11-14 21:37
Yep: If you serialize the system, you see some atoms without Lennard-Jones repulsions *and* with `sigma = 0`:
```
<Particle eps="0" q=".4102" sig="0"/>
```
This is probably the cause.

**Comment by jchodera** [comment] 2016-11-14 21:39
We should probably change the [`simtk.openmm.app.GromacsTopFile.createSystem()`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/gromacstopfile.py#L546) function so it never sets `sigma = 0` if `epsilon = 0`.

**Comment by peastman** [comment] 2016-11-14 21:47
I don't think the `sigma=0` has anything to do with it.  The problem is that if a negatively charged atom gets too close to that one, it will feel an attraction that grows without bound as they approach each other.  Of course, people still do that anyway (such as in TIP-3P), which I think is crazy, but there it is?  They rely on the oxygen's LJ repulsion to keep anything from getting too close.

I still need to verify this is really what's going on, but assuming it is, the next question is why it happens with OpenMM but not Gromacs.  There may be some other difference in the simulations.  For example, does the Gromacs one possibly have more constraints?  Or a lower temperature?  Or a smaller step size?

**Comment by peastman** [comment] 2016-11-14 23:17
Here's a graph showing what's happening to the energy over the final 100 time steps before it blows up.  The top is kinetic energy and the bottom is potential energy.

![screenshot from 2016-11-14 15 14 46](https://cloud.githubusercontent.com/assets/4379786/20286720/1f03e812-aa7d-11e6-8099-fb08a03342a1.png)

**Comment by jhprinz** [comment] 2016-11-15 09:26
@dwhswenson Is it possible that the same thing happens in our Alanine simulations? I checked that in that system there are no particles with `sig="0"` but lots of `eps="0"`. We are running at a very high temperature...

**Comment by dwhswenson** [comment] 2016-11-15 14:23
@peastman : @sroet should be able to send you Gromacs input files for comparison, although he's traveling today (and will be at a workshop for the next 10 days -- I hope he has access to his files from there). But I can tell you that we tried to match everything as well as possible: same temperature, I think the same constraints (at least, we talked about checking that). One difference I'm aware of is that, since VVVR isn't available in Gromacs (and we consider it our "baseline" as we vary other options), we used the `v-rescale` integrator ([Bussi, Donadio, Parrinello, JCP **126**, 014101](http://dx.doi.org/10.1063/1.2408420)), which is available in Gromacs.

@jhprinz : Have we still been having NaNs in AD? Switching to VVVR fixed it for me -- I ran 10k TPS shooting moves, both fixed and flexible length, and ended up with a small number (<1%) NaN. As I understood from @jchodera, that's not unexpected when doing mixed precision. Also, for AD we use OpenMM's built-in implementation of Amber 96 -- one of the peculiarities of the project causing the problem in this issue is that we're importing a custom FF from its Gromacs representation (and that would be my guess for the source of the problem).

**Comment by jhprinz** [comment] 2016-11-15 14:59
@dwhswenson Okay. No I did not have problem but remembered that you still had some even after using `VVVR`. Even better then... Never mind.

**Comment by sroet** [comment] 2016-11-15 16:51
@peastman @dwhswenson : Found some time at the airport to grab the file, here's the .mdp
[npt.mdp.zip](https://github.com/pandegroup/openmm/files/592579/npt.mdp.zip). 
Together with this webpage you should be able to figure out the options.
http://manual.gromacs.org/online/mdp_opt.html

>  For example, does the Gromacs one possibly have more constraints? Or a lower temperature? Or a smaller step size?

constraints are set to ```h-bonds``` which should only constrain the length of h-bonds, not their angles. It does however uses the LINCS algorithm

The temperature of the energy groups is 310 K (```ref_t```) and velocities are also generated at that temperature (```gen_temp```)

It also uses a larger step size(```dt```) of 0.002 ps

The Gromacs version used is 4.6.1. 

I will try to answer any other questions as soon as I have internet again

**Comment by peastman** [comment] 2016-11-16 20:25
I managed to get a record of the forces on all atoms as it blew up.  That confirms my hypothesis.  Starting about 25 time steps before the end, the forces on atoms 3019 (a water oxygen) and 11721 (a water hydrogen) began to grow, reaching enormous values (about 90000 kJ/mol/nm) a few steps before the end.  The forces on them remained roughly equal in magnitude and opposite in direction.  I also checked the DCD trajectory, and in the last recorded frame those two waters were very close to each other.

So now to figure out why this happens in OpenMM but not Gromacs.  Does anyone know if Gromacs does something strange to prevent it from happening, like capping the forces or constraining atoms from getting too close together?

**Comment by peastman** [comment] 2016-11-17 17:03
I've been experimenting with changing lots of things to see if I can narrow down the source of the problem.  Here are some things I've tried so far.  None of them made the problem go away.

- Remove the barostat
- Reduce the time step to 0.5 fs
- Increase the time step to 2 fs
- Change the constraints to `constraints=None`
- Reduce the temperature to 290 K

**Comment by peastman** [comment] 2016-11-18 18:08
Now I'm really confused.  I tried adding a LJ term to the unshielded atoms (sigma=0.1 nm, epsilon=0.06 kJ/mol, which is typical of other hydrogens), and the error still happened.

**Comment by jchodera** [comment] 2016-11-18 18:13
I'm not sure if it's related, but every project in my lab using 7.1.0
preview builds is running into sporadic but brutal nan issues right now.

**Comment by jchodera** [comment] 2016-11-19 22:50
> I managed to get a record of the forces on all atoms as it blew up. That confirms my hypothesis. Starting about 25 time steps before the end, the forces on atoms 3019 (a water oxygen) and 11721 (a water hydrogen) began to grow, reaching enormous values (about 90000 kJ/mol/nm) a few steps before the end. The forces on them remained roughly equal in magnitude and opposite in direction. I also checked the DCD trajectory, and in the last recorded frame those two waters were very close to each other.

Any chance you could share the serialized `System` and DCD trajectory?

I wonder if some of the function approximations start to behave poorly in this region (e.g. `erfc`), such that the difference between `Reference` and `OpenCL/CUDA` platforms starts to diverge during these close encounters. That could potentially explain the difference in behavior between codes.

**Comment by jchodera** [comment] 2016-11-21 15:41
On our projects that have been generating `nan`s, reverting to 7.0.1 makes them go away. 

I'm trying to set up some sort of `git bisect` + `conda build` automated script today to run a bunch of tests to see where things went wrong.

**Comment by peastman** [comment] 2016-11-21 18:55
I'm attempting to do that manually.  Note that a bug in reading Gromacs files was fixed on Aug. 4.  Any revision before that fails immediately.  You can work around it by adding the following line immediately after the call to `createSystem()`:

```Python
system.setDefaultPeriodicBoxVectors(*box_vectors)
```

**Comment by peastman** [comment] 2016-11-22 03:41
Using your script, I get the nans even with 7.0.

**Comment by peastman** [comment] 2016-11-28 19:31
I'm still working on this.  It's just going very slowly, since every test takes so long.  I have a program that runs until the coordinates become nan, then writes out serialized states for the last 150 time steps.  That lets me get a look at what's happening as it blows up.

I can clearly see atoms moving on top of each other, including ones that both have LJ terms, so they really shouldn't.  It appears something is going wrong with the force calculation.  If I load the serialized states back in and compute the forces for them, it shows an enormous repulsion between those atoms, steadily growing as they get closer together.  But the forces that were recorded in the serialized state do not show that.  They show small forces, right up until the very last step when they suddenly become huge.  For example, here's a printout of the force on one particular atom over the last few steps.  For each step, it first prints the force that was recorded in the state, then prints the force I get when I load in the state and recompute the forces.

```
146
(897.3086586892605, -868.218638241291, 1752.7663555759937) kJ/(nm mol)
(-1083289.483429538, 1184824.8739755452, -1804345.501873657) kJ/(nm mol)
147
(800.3483976125717, -917.1483402699232, 1686.1580630913377) kJ/(nm mol)
(-2044154.2138187392, 2323772.8755362034, -3536505.802964419) kJ/(nm mol)
148
(615.7071821093559, -944.4497976303101, 1554.7214903980494) kJ/(nm mol)
(-3984246.8723839186, 4700633.563346237, -7173166.345348641) kJ/(nm mol)
149
(-7644915.730126262, 9178254.001837194, -14249142.174014017) kJ/(nm mol)
(-7644915.755200796, 9178254.444322601, -14249142.187764086) kJ/(nm mol)
```

But I haven't figured out why this is happening.  I first thought there was something wrong in the logic that decides when it needs to rebuild the neighbor list, but I've pretty much convinced myself that isn't the problem.  That suggests a problem in actually building the neighbor list.  But when I reload the state and it builds the neighbor list from exactly the same coordinates, it does work correctly.  So I'm confused.

**Comment by sroet** [comment] 2016-11-29 17:33
I tried to recreate the bug with NVE, to make testing easier.
[This file](https://github.com/pandegroup/openmm/files/619690/nve_nan.tar.gz) has everything to generate NaNs with reasonable certainty after 10400 steps (4/6 tries) or 40 steps (6/6 tries) on my machine  . I hope the checkpoint/state files are deterministic enough to also generate NaNs on your machines and that this helps to speed up the testing. 

These calculations were done on 
GPU: NVIDIA GTX Titan X (Maxwell)
Driver Version: 352.79
CUDA Version: 7.5.18
openmm version: 7.0.1.dev-5e86c4f

**Comment by jchodera** [comment] 2016-11-30 23:20
@sroet : #1680 should have resolved this.

Can you test again on the latest `master`? 

If you are using `conda`, you can downgrade, wipe, and upgrade:
```
conda install --yes -c omnia openmm==7.0.1
conda clean -plti --yes
conda install --yes -c omnia/labels/dev openmm==7.1.0
```

**Comment by peastman** [comment] 2016-11-30 23:24
I don't have any reason to think #1680 fixed this.  Consider that this error appears on OpenCL as well as CUDA, while that optimization only ever existed in CUDA.  Also, I can reproduce this problem even with 7.0.1.

**Comment by jchodera** [comment] 2016-11-30 23:27
Sorry---my apologies!

**Comment by peastman** [comment] 2016-12-01 22:15
> This file has everything to generate NaNs with reasonable certainty after 10400 steps (4/6 tries) or 40 steps (6/6 tries) on my machine

Thanks, that's awesome!  I think that's going to make the debugging a lot easier.  It's already given me a good clue that the problem may be related to the triclinic box.  In this case, the pair of atoms that's getting very close together is 4681 and 5269.  At the moment when everything blows up, the displacement between them is (-3.4194440445574177, -3.454939620980135, -4.8334128886145376).  Which looks remarkably similar to the third box vector: (-3.4316, -3.4316, 4.85302).  I don't think that's a coincidence.

**Comment by peastman** [comment] 2016-12-02 00:37
Triclinic boxes give me headaches. :(

Ok, we have two atoms.  They're at (6.67268, 2.17934, 4.70907) and (3.26487, 5.57294, -0.0805301).  The displacement between them is (3.40781, -3.39359, 4.7896), which becomes (-0.0237906, 0.0380077, -0.0634189) after applying periodic boundary conditions.  They're close together.

Now, each of those atoms is part of a block of 32 atoms, so we compute a bounding box for each of those blocks.  The first one has center (6.48023, 2.18804, 4.10904) and width (0.441657, 0.445549, 0.600031).  Yep, the first atom is inside it.  The second box has center (3.8328, 5.98012, 1.7011) and width (0.567932, 0.867753, 1.78163).  The displacement between the box centers, including periodic boundary conditions, is (2.64743, 3.07112, 2.40794).  Reducing that by the box widths gives (1.63784, 1.75782, 0.0262816).  These boxes don't come anywhere near each other.  Except that they do, because triclinic unit cells are really weird, and the periodic copies whose corners come closest are not the same ones whose centers are closest.

So now I have to figure out the correct way to do that test.

**Comment by jchodera** [comment] 2016-12-02 01:52
I wonder if we're seeing some symptoms of this as well.

I recently put a new check into YANK that simply compares the potential energies (on OpenCL, using PME) of a small system before and after imaging it into the box using
```python
final_potential_1 = context.getState(getEnergy=True).getPotentialEnergy() / state.kT                                                                                                                                                                                                                                                                      
context.setPositions(final_positions)                                                                                                                                                                                                                                                                                                                     
final_potential_2 = context.getState(getEnergy=True).getPotentialEnergy() / state.kT
```
So far, this check has only tripped with small but significant deviations, but may be a symptom of some pairlist generation issues:
```
Exception: Final potential before setting periodic conditions (-47519.851514) differs from after (-47519.746212) : 0.105303
```
(in units of kT)

**Comment by peastman** [comment] 2016-12-02 01:54
Ok.  The problem is that the way we compute triclinic periodic boundary conditions isn't actually guaranteed to find the nearest periodic copy.  It's only guaranteed to find it *if* the distance to that nearest copy is less than half the smallest unit cell dimension.  Usually that's fine.  Either we'll find the nearest copy, or it's guaranteed that there's nothing within the cutoff distance.  But it's not good enough in this case, because the cutoff gets padded by the widths of the two bounding boxes.

**Comment by peastman** [comment] 2016-12-02 02:03
A simple check is to compare to the energy computed with the CPU platform.  It uses a completely different neighbor list algorithm that shouldn't have this problem.

> Exception: Final potential before setting periodic conditions (-47519.851514) differs from after (-47519.746212) : 0.105303

That's a pretty tiny difference: a relative error of less than 1e-5.  More likely that's just due to roundoff in the coordinates.

**Closed** 2016-12-06 17:43 UTC
