### ISSUE TITLE
CHARMM topology handling incorrect

### ISSUE THREAD

**Issue by rwp33** [pandegroup/openmm#2217] opened 2018-11-29 06:12 UTC
I believe there is an error in handling ligands / the first water molecule in the topology after reading with `CharmmPsfFile` (and `CharmmCrdFile`) then writing the files into a PDB using `PDBFile`. In order to test this, we read in CRD/PSF files created in CHARMM (c40b1) (which were written correctly), then used `PDBFile.writeFile(psf.topology, crd.positions, open('output.pdb', 'w'))` for writing the PDB. 

The resulting PDB:
1) renamed the second ligand residue name (chain B, which should have the resname "DHF") to the resname of the first ligand, "NDP". As such, both ligands are now named "NDP" and are also now joined into the same chain (chain B). 

...
ATOM    1278  OT2  VAL   A 161       -17.113   1.724  32.954  1.00  0.00           O  
TER        1279           VAL   A 161
HETATM 1280 AC4'  NDP B     1     -26.855  20.694  12.751  1.00  0.00           C   <-- Correct
... 
HETATM 1354 NH72 NDP B     1      -17.735  24.270  25.175  1.00  0.00           H  <--Correct, resname should be "NDP"
HETATM 1355    N1    NDP B    1     -14.733  23.576  23.836  1.00  0.00           N  <-- Incorrect, resname should be "DHF" (not NDP) and in separate segment
...

2) changed the first water (original residue name "OH2", atom number 1406) to residue name "NDP", within the same chain as NDP (chain B), and placed a "TER" declaration immediately after this water (separating it from the rest of the waters, which are in chain D).

...
HETATM 1405  H14  NDP B   1     -17.675  23.652  20.592  1.00  0.00           H  <-- Incorrect, resname should be "DHF" (not NDP) and separate from chain B
HETATM 1406  OH2 NDP B   1     -30.140  23.144  16.564  1.00  0.00           O  <-- Incorrect (this is a water) resname should be "HOH" (not NDP)and in chain D
TER         1407           NDP B   1 <-- Incorrect placement of TER statement
HETATM 1408  OH2 HOH D   1     -27.808  26.743  17.833  1.00  0.00           O  <-- Correct, except should be second water of segment, not first
...

In addition, it outputs an error of `CharmmPSFWarning: Detected PSF molecule section that is WRONG. Resetting molecularity.`

I am relatively new to OpenMM so I am not sure if it is `CharmmPsfFile` that is incorrectly handling (I suspect it is), or `PDBFile`.

[pdbfix.zip](https://github.com/pandegroup/openmm/files/2627785/pdbfix.zip)

**Comment by peastman** [comment] 2018-12-03 18:54
I'm a bit confused by your PSF file.  The residue IDs start at 1 and go up to 161, then abruptly jump back to 1 again.  It then lists multiple residues that are clearly intended to be different, but that all have ID 1, which is why OpenMM is viewing them as a single residue.  I'm not sure whether OpenMM is misinterpreting the file, or whether the file is invalid.  I've been searching for any sort of official documentation on the PSF format, but haven't come up with anything.  Do you know if there's a spec that describes how this is supposed to be interpreted?

**Comment by rwp33** [comment] 2018-12-20 21:46
The PSF was generated in CHARMM (version c40b1), so I would assume it is correct (it is the same / similar to all other PSFs I have generated before). I believe that CHARMM restarts numbering for all residues in a different segment, which is determined by the SEGID. Therefore, SEGIDs HETA, HETB and HOH all restart numbering in the CHARMM PSF. I believe there is documentation about the PSF in the original CHARMM paper (J Comp Chem 1983,4, 187-217); however, I do not believe it gives much of a detailed description and I have yet to find any other detailed descriptions as well. I have attached my basic understanding of each column within the first section of the CHARMM PSF below.
[PSF.pdf](https://github.com/pandegroup/openmm/files/2700631/PSF.pdf)

**Comment by peastman** [comment] 2018-12-20 23:21
That makes sense.  It sounds like the problem is here: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L705.  It only checks to see if the residue ID has changed, but it also should check to see if the segment ID has changed.

**Comment by peastman** [comment] 2018-12-20 23:34
The fix is in #2231.  Can you try it out and see if everything now works as you expect it to?

**Closed** 2019-01-08 20:30 UTC
