### ISSUE TITLE
OpenCL platform incorrectly claims to support double precision

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1786] opened 2017-04-16 02:00 UTC
My MacBook Pro (Retina, 13-inch, Early 2015) running OS X 10.11.6 appears to claim that the OpenCL platform supports double precision and yet fails to run in `mixed` precision mode:
```
lski1962:integrator-benchmark choderaj$ python
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm
>>> platform = openmm.Platform.getPlatformByName('OpenCL')
>>> from openmmtools import testsystems
>>> t = testsystems.AlanineDipeptideVacuum()
>>> integrator = openmm.VerletIntegrator(1.0)
>>> context = openmm.Context(t.system, integrator, platform)
>>> del context
>>> platform.setPropertyDefaultValue('Precision', 'mixed')
>>> from openmmtools import testsystems
>>> t = testsystems.AlanineDipeptideVacuum()
>>> integrator = openmm.VerletIntegrator(1.0)
>>> context = openmm.Context(t.system, integrator, platform)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 6269, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible OpenCL platform is available
```
Note that it works fine in the default (`single`) precision.

Is this the correct behavior for `supportsDoublePrecision()`? If so, maybe we can add a `supportsMixedPrecision()` method?

**Comment by peastman** [comment] 2017-04-17 16:40
The API documentation for that method (http://docs.openmm.org/7.1.0/api-c++/generated/OpenMM.Platform.html#_CPPv2NK6OpenMM8Platform23supportsDoublePrecisionEv) states:

> Deprecated
>
> This method is not well defined, and is too simplistic to describe the actual behavior of some Platforms, such as ones that offer multiple precision modes. It will be removed in a future release.

**Comment by jchodera** [comment] 2017-04-17 17:01
Ah! I had only made it as far as the table that just had the first line:
![image](https://cloud.githubusercontent.com/assets/3656088/25095801/4ed7a4e0-236b-11e7-96a6-8c091d880b7c.png)
Is there a replacement method for querying whether `mixed` precision is available on a platform? Or do we just have to try to create a `Context`, see if it fails, and clean up the `Context` if it succeeds in order to find out?

Alternatively, is there a way to ask for the fastest platform that supports specific platform options for this system? The problem is that the `platform` argument to `Context` can't be omitted if `platform_options` is specified.

**Comment by peastman** [comment] 2017-04-17 17:16
> Alternatively, is there a way to ask for the fastest platform that supports specific platform options for this system?

No.  If you're specifying options, you have to chose a specific platform.  That's because different platforms support different options.  You could of course loop over platforms and stop when you reach one that doesn't throw an exception.

Remember that "mixed precision" is only defined in the context of a given platform.  OpenCL and CUDA each give a choice of three precision modes.  If you're running on an NVIDIA GPU, they mean the same things by them.  But if you're running on a non-NVIDIA GPU, it's possible the OpenCL platform will do some of its numerics in a different way.  Reference doesn't give a choice, and uses double precision for everything.  CPU doesn't give a choice and uses a mix of single and double precision, but it's not exactly the same mix that OpenCL and CUDA use.

**Comment by peastman** [comment] 2017-12-05 23:36
Closing this since it's not a bug, just a deprecated feature.

**Closed by peastman** 2017-12-05 23:36 UTC
