### ISSUE TITLE
CHARMM36 termini patches are not recognized/handled

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#2047] opened 2018-04-12 23:04 UTC
Hi all,

I have been trying to setup a simulation of a peptide in water using CHARMM36 and capped termini (`ACE` and `CT3`) but I cannot get past loading the structure. I prepared the PDB using VMD (psfgen) and everything seems fine - check [here](https://gist.github.com/JoaoRodrigues/425b2960fb9d4aad0f9de875d5699a51). The atom names match those on the `charmm36.xml` forcefield file for the `ACE` and `CT3` patches. Any clues? Is there a way of specifying patches that I am not following?

Here's a self-contained example:
```
import simtk.openmm.app as app
pdb = app.PDBFile('peptide.pdb')
ff = app.ForceField('charmm36.xml')
model = app.Modeller(pdb.topology, pdb.positions)

# This is just a trick to cause the error
# Keeping hydrogens and trying to create a system results in the same issue
hydrogens = [a for a in model.topology.atoms() if a.element == app.element.hydrogen]
model.delete(hydrogens)
model.addHydrogens(forcefield=ff, pH=7.0)
```

This gives the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-9889d0fd1625> in <module>()
----> 1 model.addHydrogens(forcefield=ff, pH=7.0)

/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/modeller.pyc in addHydrogens(self, forcefield, pH, variants, platform)
    840             # Use the ForceField the user specified.
    841
--> 842             system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic)
    843             atoms = list(newTopology.atoms())
    844             for i in range(system.getNumParticles()):

/usr/local/lib/python2.7/dist-packages/simtk/openmm/app/forcefield.py in createSystem(self, topology, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, removeCMMotion, hydrogenMass, residueTemplates, ignoreExternalBonds, switchDistance, flexibleConstraints, **args)
   1131                             break
   1132             if matches is None:
-> 1133                 raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
   1134             else:
   1135                 data.recordMatchedAtomParameters(res, template, matches)

ValueError: No template found for residue 1 (MET).  The set of atoms is similar to AOBT, but it is missing 3 atoms.
```

**Comment by jchodera** [comment] 2018-04-16 02:53
My guess is that the problem is that your PDB file does not comply with the [PDB format standard](http://www.wwpdb.org/documentation/file-format) because it is missing `CONECT` records defining bonds in your termini. The PDB standard requires that any non-standard amino acids (such as your ACE and NH2 modified termini) must specify `CONECT` residues. The result is that OpenMM only knows to fill in the missing standard bonds, but doesn't know about how the other atoms are bonded. Since OpenMM uses the element identities and connectivity to match residue templates, this causes matching to fail---unfortunately in this case with a confusing error message.

Do you have a PSF file you could use instead (which should carry the connectivity), or generate a compliant PDB file with some other tool?

**Comment by JoaoRodrigues** [comment] 2018-04-16 03:47
Hi @jchodera 

Ah, that makes some sense. Thanks. I tried a few different combinations of PDB and PSF files, not sure I tried one with proper `CONECT` statements. Should the ACE/NME be defined as separate residues? As for using the PSF, I got it from VMD as well, but it cannot match the patch to a single template: gives me a few different ones that matched. I will reproduce this tomorrow and post the messages here. 

In any case, it would be probably better to get somewhat better documentation on using CHARMM forcefields in OpenMM. Once I figure out this particular case (which is pretty standard), I can write a tutorial so that there is a guide somewhere.

**Comment by jchodera** [comment] 2018-04-16 03:58
For CHARMM, OpenMM will automatically construct residue templates made from the application of compatible `PATC` x `RESI` pairs, so you shouldn't separate out ACE or NME as separate residues. 

If you *can* post the PSF file, that would be a huge help in debugging!

> In any case, it would be probably better to get somewhat better documentation on using CHARMM forcefields in OpenMM. Once I figure out this particular case (which is pretty standard), I can write a tutorial so that there is a guide somewhere.

I totally agree! This is one area where we can use a great deal of improvement.

**Comment by JoaoRodrigues** [comment] 2018-04-16 04:04
>If you can post the PSF file, that would be a huge help in debugging!

Will do tomorrow then, easy to get/regenerate. Thanks again!

**Comment by JoaoRodrigues** [comment] 2018-04-16 22:10
Update 1:

Reading in the PSF to provide a topology and the forcefield XML (because I have modified aminoacids that I put in there):

```
#!/usr/bin/env python

import simtk.openmm.app as app

mol = app.PDBFile('peptide_wt_capped.pdb')
psf = app.CharmmPsfFile('peptide_wt_capped.psf')
ff = app.ForceField('charmm36.xml')

model = app.Modeller(psf.topology, mol.positions)
system = ff.createSystem(model.topology, nonbondedMethod=app.NoCutoff)
```

```
Traceback (most recent call last):
  File "test_psf.py", line 10, in <module>
    system = ff.createSystem(model.topology, nonbondedMethod=app.NoCutoff)
  File "/home/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1112, in createSystem
    unmatchedResidues = _applyPatchesToMatchResidues(self, data, unmatchedResidues, bondedToAtom, ignoreExternalBonds)
  File "/home/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1518, in _applyPatchesToMatchResidues
    [template, matches] = forcefield._getResidueTemplateMatches(res, bondedToAtom, patchedTemplateSignatures, ignoreExternalBonds)
  File "/home/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 879, in _getResidueTemplateMatches
    raise Exception('Multiple matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple matching templates found for residue 1 (MET): MET-ACED, MET-ACE, MET-ACPD, MET-ACP.
```

**Comment by JoaoRodrigues** [comment] 2018-04-16 22:27
As for including the `CONECT` records, still gives an error. PDB file [here](https://gist.github.com/JoaoRodrigues/ce75bc81191fc68eef72b26019382ed2).

```
import simtk.openmm.app as app

pdb = app.PDBFile('peptide_wt_pymol_cap.pdb')
ff = app.ForceField('charmm36.xml')
model = app.Modeller(pdb.topology, pdb.positions)

# This is just a trick to cause the error
# Keeping hydrogens and trying to create a system results in the same issue
hydrogens = [a for a in model.topology.atoms() if a.element == app.element.hydrogen]
model.delete(hydrogens)
model.addHydrogens(forcefield=ff, pH=7.0)
```

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    model.addHydrogens(forcefield=ff, pH=7.0)
  File "/home/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/modeller.py", line 842, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic)
  File "/home/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1133, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (MET).  The set of atoms is similar to AOBT, but it is missing 3 atoms.
```

**Comment by jchodera** [comment] 2018-04-17 05:03
@peastman : The multiple matching templates error [here](https://github.com/pandegroup/openmm/issues/2047#issuecomment-381766398) concerns me---it looks like we are ending up with multiple residue x patch automated combinations that create the same residue template:
```
Exception: Multiple matching templates found for residue 1 (MET): MET-ACED, MET-ACE, MET-ACPD, MET-ACP.
```
I'm not quite sure how we want to handle this. Clearly, `ForceField` can only support unique template graphs. How should we handle this in the conversion?

I've put all the files (renamed), including a short script here:
[termini.zip](https://github.com/pandegroup/openmm/files/1918178/termini.zip)

I also still don't understand why the PDB with `CONECT` records doesn't yield the same error. When I just use loaded `PDBFile` `topology`, I get yet a different error:
```
lski2414:termini choderaj$ python -i test.py 
Loading CHARMM forcefield...
Creating system...
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    system = ff.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1133, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (MET).  The set of atoms is similar to MBSM, but it is missing 9 hydrogen atoms.
```

**Comment by JoaoRodrigues** [comment] 2018-04-17 17:31
@jchodera @peastman Would it be an option to consider having an optional argument to `createSystem` where you can provide a dictionary of patches you want to apply? For example:

```
...
system = ff.createSystem(mol.topology, patches={'ACE': 1, 'CT3': 27, 'DISU': [(24, 65), (25, 93)]}
```

The default behavior would be the current one where the system would try to guess. Otherwise it might be too hard of a problem to solve and you will have to end up making some decisions on behalf of the user.

**Comment by jchodera** [comment] 2018-04-17 18:07
We [discussed this possibility earlier](https://github.com/pandegroup/openmm/issues/1335#issuecomment-172049698) but decided to try to make automatic patching work. However, I think it's becoming so problematic that we should rethink the approach to automated patching and require user-specified patches for now for all but the simplest cases (N- and C-terminal whitelisted patches), perhaps reintroducing the automated patching later.

@peastman : What do you think?

**Comment by jchodera** [comment] 2018-04-17 18:42
How would we want to check for duplicates, and which duplicates should be removed?
* Check that patches are identical? What information must match for patches to be identical?
* Check for patch x residue combinations that are identical? Again, what information must match?
* Check that the resulting XML for patches are identical?
* Check that the resulting XML for patches residues is identical?

My guess is that we should be checking the XML of the Patch, discarding any encountered that are identical since it doesn't matter which one we keep. Is there some way we can expose a public API method in ForceField that takes two XML Patch or Residue definitions to check if they are identical? I worry that having this functionality in both OpenMM and ParmEd is a recipe for having them get out of sync quickly.

**Comment by peastman** [comment] 2018-04-17 18:49
Just checking patches (not patch/residue combinations) is hopefully sufficient.  At least, we don't yet know of any situations where it isn't, so let's only deal with that case for now.

The safest way to do the comparison is probably to check that the generated XML is identical (other than the patch name, of course).

**Comment by jchodera** [comment] 2018-04-17 19:05
> The safest way to do the comparison is probably to check that the generated XML is identical (other than the patch name, of course).

We don't need to worry about element order?

**Comment by JoaoRodrigues** [comment] 2018-04-17 19:13
>But OpenMM figures that out automatically, so that difference disappears when the force field is translated.

Are we absolutely sure this is the case? Not doubting, just double-checking. ACE, ACED, ACP, ACPD are all the same patch but they apply to different linkages (standard, dipeptide, proline, dipeptide+proline). If this is a matter of applying different force field terms (e.g. CMAP) how sure are we that we will apply the right ones?

**Comment by peastman** [comment] 2018-04-17 19:13
> We don't need to worry about element order?

Does ParmEd produce them in a deterministic order?  I was assuming it did, since the duplicate definitions I looked at were all identical.  If you don't think that will be robust, we could instead compare the data structures it generates them from.

**Comment by JoaoRodrigues** [comment] 2018-04-17 19:17
Also, about removing the patches, this should be explicitly stated somewhere then. It will be very confusing for users to have a 'hidden' layer that matches different patches to a same one but then applies the right parameters under the hood.

**Comment by peastman** [comment] 2018-04-17 20:14
There won't be any hidden layer: this will be strictly part of how we translate the force field definitions from CHARMM format to OpenMM format.  There's already a lot of complexity in how that translation gets done, and this will add one more bit to it.  But OpenMM force field definitions will continue to behave exactly the same way they currently do.  If you have two identical patch definitions, it will (correctly) complain that it doesn't know which one to use, just as it does now.

Given how much complexity there is in the translation, it's very hard to be absolutely certain the two definitions will always perfectly coincide.  The best we can do is test it on a bunch of cases (and we clearly need more of them) where we start from a PDB file, evaluate the energy with both CHARMM and OpenMM, and make sure they match.

**Comment by JoaoRodrigues** [comment] 2018-04-17 21:51
>There won't be any hidden layer: this will be strictly part of how we translate the force field definitions from CHARMM format to OpenMM format.

I meant for the end-user of OpenMM. Someone with a system like mine, but with a PRO as the first residue will have `ACP` applied while someone with a MET will have `ACE`. That's what I meant by 'hidden' layer. If the termini are the only situation where patches are 'duplicated', then I am fine this simplifcation, but otherwise I suggest a message or warning where the patches are explicitly listed. Even if only for reproducibility's sake.

**Comment by peastman** [comment] 2018-04-17 22:02
That won't happen, because there won't be a ACP patch.  The only patch defined in the force field for this situation will be ACE.  Currently the XML file contains four different `<Patch>` tags whose contents are completely identical except for the patch name.  We're going to remove three of them.

Patches mean something kind of different in CHARMM and OpenMM.  In CHARMM, you explicitly "apply a patch" to modify some aspect of your system (add or remove atoms, add or remove bonds, etc.).  In OpenMM it's assumed that your topology already contains exactly the atoms and bonds you want.  (If it doesn't, that's a job for Modeller, not ForceField.)  "Patches" are just a shortcut for automatically generating lots of different templates for assigning force field parameters.

**Comment by JoaoRodrigues** [comment] 2018-04-17 22:11
> In OpenMM it's assumed that your topology already contains exactly the atoms and bonds you want.

This is a pretty big assumption, but I understand completely that from your perspective, you can't build a system that fits everyone's needs.  It's pretty easy to generate PDB files with pdbfixer for AMBER, but CHARMM is still a problem. So, as a suggestion, if OpenMM can digest PDB files coming from psfgen you've got a pretty good setup that is reproducible and testable.

Also, I understand that there won't be `ACP` patches around, and I completely agree. They just have different names in CHARMM because of the way the code is written there. OpenMM is far more flexible. I am just thinking of someone coming from a CHARMM background that goes looking for an ACP patch and cannot find it. Again, tutorials and documentation should make this very clear! Once this is fixed, I can provide a bunch of test files and examples.

**Comment by jchodera** [comment] 2018-04-17 22:27
> Does ParmEd produce them in a deterministic order? I was assuming it did, since the duplicate definitions I looked at were all identical. 

I've made some changes to ParmEd during this process to use `OrderedDict`s to preserve ordering whenever possible, but (1) there is no guarantee that the PATChes in CHARMM will always be in the same order if identical just because a few we looked at were in the same order, and (2) there is nothing encoded in either the XML or PATCh format that requires the ordering to be preserved. In fact, the XML didn't even originally preserve the order of either tags or attributes, which is why the `ffxml` files appeared to keep changing even when they had the same content---this is hopefully fixed now, to preserve the order in which the CHARMM parameter sets are read in.

> If you don't think that will be robust, we could instead compare the data structures it generates them from.

That would be much better. I'm trying to see if there's a way to do this with `lxml`, but I suspect there isn't an easy way to do so. This is why I was wondering if we could put the functionality into OpenMM so it didn't need to be duplicated.

**Comment by jchodera** [comment] 2018-04-18 23:45
@peastman: What's our plan here for proceeding?

I think I can easily add a quick comparison of Patch data structures. It's probably easiest to call duplicate patches when the parameter set is converted to OpenMM in ParmEd. I just need to know what a check for equality should entail, since CHARMM specifies more data elements than OpenMM makes use of.

I'll also note that it is not easy to add more examples for cross comparison between CHARMM and OpenMM precisely because we insist on not supporting files prepared via standard CHARMM tools. Everything must be prepared meticulously and manually, meaning my very limited time will essentially guarantee we have poor test coverage. If we had an automated way of remediating CHARMM files, it would make it easy to prepare a variety of tests.

**Comment by peastman** [comment] 2018-04-19 00:12
> This is why I was wondering if we could put the functionality into OpenMM so it didn't need to be duplicated.

I don't see how this could work.  The filtering has to be done in ParmEd before the XML file has been generated.  That dictates it has to be done based on ParmEd data structures.

>  I just need to know what a check for equality should entail, since CHARMM specifies more data elements than OpenMM makes use of.

Anything that affects the XML that gets written.  I can't be more specific without researching what the ParmEd data structures look like, but that answer is pretty much complete.  If it affects the XML, it needs to match.

> we insist on not supporting files prepared via standard CHARMM tools.

It's not something we insist on.  Their PDB files simply don't contain enough information to construct a proper Topology based on them.  They strip out essential information, relying on the PSF file to store that information instead.

That said, you should be able to easily restore the information in an automated way.  Load both the PDB file and the PSF file into OpenMM.  Then call `PDBFile.writeFile()`, giving it the Topology from the PSF file and the positions from the PDB file.

**Comment by jchodera** [comment] 2018-04-20 18:42
Quick update: Haven't had any free cycles to tackle these until now, but plan to finish up the duplicate-patch culling this afternoon and get @peastman updated patches by the end of the day. I'll test on my end over the weekend in parallel.

I'll also refresh my memory on why I had trouble with the PSF->PDB conversions.

**Comment by peastman** [comment] 2018-04-20 19:18
> I'll also refresh my memory on why I had trouble with the PSF->PDB conversions.

In principle you don't even need to convert to a PDB.  You could just load the PSF, get its Topology, and pass that to the ForceField's `createSystem()`.

**Comment by JoaoRodrigues** [comment] 2018-04-20 19:30
>I'll also refresh my memory on why I had trouble with the PSF->PDB conversions.

PSF files, if I recall correctly, do not store coordinates so you shouldn't even try converting. You could, maybe, combine both to add `CONECT` records to PDBs but that's a messy hack, specially since everybody is (should be?) moving to mmCIF.

I believe what @peastman suggests is the best approach for this: PSFs can be loaded to provide the topology for the system, along with PDBs for positions.

By the way, somebody asked me the other day what qualities an open source project needed to have in order to succeed and grow a community and I gave OpenMM/you as an example: good user support. Thank you for all your efforts in fixing all this!

**Comment by JoaoRodrigues** [comment] 2018-04-20 19:33
>That said, you should be able to easily restore the information in an automated way. Load both the PDB file and the PSF file into OpenMM. Then call PDBFile.writeFile(), giving it the Topology from the PSF file and the positions from the PDB file.

A quick comment on this. For a variety of reasons, I have been using mmCIF files as a default in OpenMM. I'm not sure they already do this, but you could use that format to export both coordinates and topology information in a 'standardized' way that could be read later. There are already some fields that OpenMM uses in mmCIF files to provide extra information (e.g. periodic box vectors) so it wouldn't be that farfetched?

**Comment by peastman** [comment] 2018-04-20 19:38
Ultimately we just need a Topology object we can pass to `createSystem()`.  It doesn't care where it came from, so any type of file that can produce a Topology will work: PDB, PSF, etc.

**Comment by jchodera** [comment] 2018-04-24 02:35
Duplicate patches are now being culled: https://github.com/choderalab/openmm-forcefields/pull/64

**Closed** 2018-05-03 00:40 UTC

**Comment by peastman** [comment] 2018-05-03 00:43
Can you give details on what hydrogens are not getting added?  It adds them based on this file: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/hydrogens.xml.  It's done strictly by residue name, not by matching templates or anything like that.

**Comment by JoaoRodrigues** [comment] 2018-05-03 00:48
Any, really. If I remove the hydrogens of the structure (or provide one without any) and then try `addHydrogens` it fails. See my first message here, that's exactly the error. Using `CONECT` records, PSF files, etc, does not help, the process fails at the template matching step inside `addHydrogens`.

**Comment by jchodera** [comment] 2018-05-03 00:51
@peastman: The `hydrogens.xml` file does contain ACE and MET residues, but not patched forms of every residue, so it wouldn't know how to add protons for CHARMM termini.

A potential workaround would be to generate a `charmm36-hydrogens.xml` file that would contain proton definitions for all residues, or to allow Modeller to obtain hydrogen definitions from a ForceField object.

**Comment by peastman** [comment] 2018-05-04 00:57
I think I see.  Because Amber defines ACE as its own residue, but CHARMM defines it as a modification to another residue?

**Comment by jchodera** [comment] 2018-05-05 17:48
From our discussion with @peastman yesterday, everything is now behaving as it was designed even though you cannot pass the same PDB file through both `app.Modeller` and `app.ForceField` and expect to be able to assign CHARMM36 parameters.  We'll revisit that workflow problem in a future OpenMM release, and try to address this problem with documentation and suggestions for the current release.
