### ISSUE TITLE
Is it possible to delete a GPU context to save memory?

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#1501] opened 2016-05-26 22:57 UTC
Hi there,

I'm not sure if this is a developer issue or a user issue, so I'll just post it here.  

ForceBalance often creates many simulation objects in the same process in order to calculate the different quantities for fitting the force field parameters.  For a particular calculation that we are running, it will fail with the call stack below.  This happens after ForceBalance has already been running and successfully calling OpenMM functions for a few minutes.

When I monitor the GPU memory usage with nvidia-smi, I see that the memory usage continues to go up until it hits the upper memory limit, which coincides with ForceBalance crashing with this error message.  Because of this, I think the problem may be due to the device memory becoming full when it creates too many GPU contexts.

For this calculation, ForceBalance does not require all of these contexts to exist simultaneously, so I think the issue could be resolved if I knew how to free the device memory.  If I delete the Simulation object in Python, does that also free the host and device memory of the GPU context?

Thanks a lot,
- Lee-Ping

```
Traceback (most recent call last):
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ForceBalance.py", line 43, in Run_ForceBalance
    optimizer.Run()
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/optimizer.py", line 309, in Run
    xk = self.OptTab[self.jobtype]()
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/optimizer.py", line 897, in NewtonRaphson
    return self.MainOptimizer(b_BFGS=0)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/optimizer.py", line 481, in MainOptimizer
    data        = self.Objective.Full(xk,Ord,verbose=True)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/objective.py", line 271, in Full
    Objective = self.Target_Terms(vals, Order, verbose, customdir)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/objective.py", line 213, in Target_Terms
    Ans = Funcs[Order](mvals, customdir=customdir)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/target.py", line 310, in get_H
    Ans = self.meta_get(mvals,1,1,customdir=customdir)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/target.py", line 565, in meta_get
    Answer = self.get(mvals, AGrad, AHess)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/interaction.py", line 187, in get
    emm = callM(mvals)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/interaction.py", line 184, in callM
    return self.engine.interaction_energy(self.select1, self.select2)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/openmmio.py", line 1079, in interaction_energy
    A = self.A.energy()
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/openmmio.py", line 959, in energy
    return self.evaluate_(traj=True)["Energy"]
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/openmmio.py", line 928, in evaluate_
    self.update_simulation()
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/openmmio.py", line 853, in update_simulation
    self.create_simulation(**self.simkwargs)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/forcebalance-1.3.2-py2.7-linux-x86_64.egg/forcebalance/openmmio.py", line 792, in create_simulation
    self.simulation = Simulation(self.mod.topology, self.system, integrator, self.platform)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4275, in __init__
    this = _openmm.new_Context(*args)
Exception: No compatible CUDA device is available
```

**Comment by jchodera** [comment] 2016-05-26 23:01
Python is very lazy about garbage collection, and probably isn't at all concerned with the limitations of GPU memory.  It's good practice when using OpenMM to always clean up your `Context` object after you are done with it.  For example:
```python
# Create a context and compute the potential energy
integrator = VerletIntegrator(0.001)
context = Context(system, integrator)
context.setPositions(positions)
potential = context.getState(getEnergy=True).getPotentialEnergy()
# Clean up!
del context, integrator
```

**Comment by peastman** [comment] 2016-05-26 23:20
As far as the C++ API is concerned, it's definitely the case that when a Context gets destructed, it deletes its GPU context.  The problem is making sure that Python actually deletes the Context.  The `del` keyword doesn't actually delete the object.  It just deletes the reference to it from the current namespace.  Once all references are gone, it can be garbage collected.

I'm not too up to date on how Python handles garbage collection.  It used to rely primarily on reference counting, with a mark/sweep collector to deal with loops.  Perhaps that's still the case?  If so, presumably the Context will get deleted as soon as there are no longer any references to it.  Anyway, it should be easy to test whether that fixes your problem.

**Comment by peastman** [comment] 2016-05-26 23:28
You can also force a full garbage collection like this:

```Python
import gc
gc.collect()
```

**Comment by jlmaccal** [comment] 2016-05-26 23:31
> 
> As far as the C++ API is concerned, it's definitely the case that when a Context gets destructed, it deletes its GPU context. The problem is making sure that Python actually deletes the Context. The del keyword doesn't actually delete the object. It just deletes the reference to it from the current namespace. Once all references are gone, it can be garbage collected.
> 
> I'm not too up to date on how Python handles garbage collection. It used to rely primarily on reference counting, with a mark/sweep collector to deal with loops. Perhaps that's still the case? If so, presumably the Context will get deleted as soon as there are no longer any references to it. Anyway, it should be easy to test whether that fixes your problem.
> 
> 

My understanding is the same as yours. Objects are deallocated as soon as their reference count hits zero. Cycles are detected occasionally using a mark-and-sweep type algorithm. There’s little reason why one should have to manually ever call `del` on an object. Something fishy seems to be going on.

**Comment by peastman** [comment] 2016-05-26 23:33
> There’s little reason why one should have to manually ever call `del` on an object. Something fishy seems to be going on.

Remember, `del` deletes the reference, not the object.  As long as that reference is still around, the object can never be garbage collected.

**Comment by jlmaccal** [comment] 2016-05-26 23:35
> Remember, del deletes the reference, not the object. As long as that reference is still around, the object can never be garbage collected

I understand this, but I wasn't clear. `del` decrements the reference count. But so does anything else that unbinds a name from the object. So there's no reason that calling `del` should free memory when the variable going out of scope doesn't, as John's example would indicate. If this does result in different behavior, then something strange is going on.

**Comment by peastman** [comment] 2016-05-26 23:41
If it actually goes out of scope at that point then yes, it shouldn't be necessary.  I assumed his code was meant to be in the middle of a larger function, with other things happening later that don't require the Context.

**Comment by leeping** [comment] 2016-05-27 03:11
It's indeed in the middle of a larger function, with other things happening later that don't require the context.  I'll try deleting the context in a few places and get back to you.

**Comment by leeping** [comment] 2016-05-27 03:12
Also, thanks to everyone for the helpful suggestions!

**Comment by peastman** [comment] 2016-08-17 19:52
@leeping did deleting the context work?  Can this issue be closed?

**Comment by yudongqiu** [comment] 2016-08-23 18:36
@peastman We ended up deleting the Simulation object after evaluating each target in each Forcebalance optimization iteration. This will result in recreating the Simulation objects in each Forcebalance optimization step, introducing minimal performance loss but it will save us from the insufficient GPU memory problem. Thanks a lot and I think this issue can be closed.

**Comment by peastman** [comment] 2016-08-23 18:37
Thanks!

**Closed** 2017-01-06 18:07 UTC
