### ISSUE TITLE
Neighborlists for CustomNonbondedForce with interaction groups

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2010] opened 2018-03-07 18:21 UTC
cc: #1980 

To implement algorithms like [g-BAOAB with solute/solvent splitting](http://rspa.royalsocietypublishing.org/content/472/2189/20160138) which allows the outer timestep to be increased to 8-9 fs, we need to split out a force group to handle solute-solute and solute-solvent (direct space) interactions. While this can be done with `CustomNonbondedForce` with interaction groups, it is not efficient because interaction groups are not yet able to use pairlists.

It would be useful to add pairlist support for interaction groups. Either the user could make this choice when defining the interaction via an optional argument
```python
force.addInteractionGroup(set1, set2, usePairlist=True)
```
or a simple heuristic based on the number of particles in each group (or fraction of particles in the system in each group) could likely be very successful.

**Comment by peastman** [comment] 2018-03-07 22:25
This looks like a duplicate of #1765?

**Comment by jchodera** [comment] 2018-03-07 22:45
Whoops! It is, but I didn't find one in a quick search. 

Feel free to close one of these issues.

**Closed** 2018-03-07 22:56 UTC
