### ISSUE TITLE
Weird performance issue

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1496] opened 2016-05-20 01:15 UTC
I'm running into a very strange performance issue, where occasionally time steps take far, far longer than expected.

Ubuntu 14.04
GTX 780
CUDA-7.5
Driver 352.93
OpenMM compiled from git head branch

Here is a repository that reproduces the issue on my machine:
<https://github.com/jlmaccal/openmm_debug>

I added code to `simulate.py` to wrap the call to `self.integrator.step(10)` around line 195. This results in the following:
```
<snipped>
integrated: 0.000982999801636
integrated: 0.000885963439941
integrated: 0.00081992149353
integrated: 0.0997700691223
integrated: 0.000754117965698
integrated: 0.247699022293
integrated: 0.000504970550537
integrated: 0.00102114677429
integrated: 0.267261981964
integrated: 0.000370025634766
integrated: 0.000837087631226
integrated: 0.000730991363525
integrated: 0.09441614151
integrated: 0.000996112823486
integrated: 0.0987889766693
integrated: 0.000802993774414
integrated: 0.000730037689209
integrated: 0.0980548858643
integrated: 0.000950813293457
integrated: 0.000948905944824
integrated: 0.00103306770325
integrated: 0.097736120224
integrated: 0.000970125198364
integrated: 0.101416110992
integrated: 0.000514030456543
integrated: 0.000550985336304
integrated: 0.248163938522
integrated: 0.000985860824585
7000	-969104.429238	14.2
integrated: 0.000369071960449
integrated: 0.000373125076294
integrated: 3.79387688637
integrated: 0.000580787658691
integrated: 0.092945098877
integrated: 0.000379085540771
integrated: 0.00102114677429
integrated: 0.0990219116211
integrated: 0.000706911087036
integrated: 0.000934839248657
integrated: 0.000591039657593
integrated: 0.0998561382294
integrated: 0.000793933868408
integrated: 0.0989849567413
integrated: 0.000677108764648
integrated: 0.000731945037842
integrated: 0.0983250141144
integrated: 0.000701904296875
integrated: 0.000677108764648
integrated: 0.000725030899048
integrated: 0.0994501113892
integrated: 0.000982046127319
integrated: 0.0952799320221
integrated: 0.00094199180603
integrated: 0.00102806091309
integrated: 0.125684976578
integrated: 0.000361919403076
integrated: 0.000840902328491
integrated: 0.000749111175537
integrated: 0.0969178676605
integrated: 0.00098705291748
integrated: 0.100377082825
integrated: 0.000785112380981
<snipped>
```

There are two things that are strange.

## Really slow timesteps

First, it takes on the order of a few tens of milliseconds to integrate each batch of 10 timesteps, on average. However, there is one batch where it takes 3.8 seconds to integrate 10 time steps! 

Provided I set the random seed for the integrator and barostat, this is reproducible on my machine and always happens at the same point. If I change the seed or constraints, etc, there are still the same weird pauses, but at different places.

I then ran some diagnostics using `nvprof`. There are a few weird things in `summary.dat`. For example, there is at least one call to `computeNonbonded` that takes 50 times longer than average. There is also a call to `cuMemcpyDtoH` that takes more than 3 seconds, when the average is ~20ms.

I also did a trace with `--print-gpu-trace` and `--print-api-trace` enabled. The output is a different run from the summary statistics, but you can see the strange call to `cuMemcpyDtoH` on line 226081 of `prof.dat`, while the strange call to `computeNonbonded` is on 217545.

I have no clue what's going on. But in our actual MELD simulation this is happening quite frequently, sometimes occurring multiple times in the span of 1000 timesteps, which really slows things down. I haven't been able to identify what's different in these simulations that makes it more frequent. This is a simple REMD simulation with no extra forces added beyond what the force field adds.

## Oscillatory behavior of time to compute timesteps

There is a strange oscillatory pattern to the time it takes to compute 10 time steps (see `timing.dat`). Typically, there are 2 or 3 batches of 10 timesteps that complete very quickly, followed by one that is 10-20 times slower. I'm not sure if this is normal, due to building neighborlists or something, but it struck me as weird.

**Comment by rmcgibbo** [comment] 2016-05-20 02:04
Is it possible that this is a driver issue, potentially pausing execution because of high temperatures or other programs that want to use the gpu?

**Comment by jlmaccal** [comment] 2016-05-20 02:37
It could be a driver issue, but I don't think it's either of the others as it happens at the same time in every run. I've also killed X and as many processes as I can, but this makes no difference. When I'm in tomorrow, I'll try to monitor the temperatures.

**Comment by jlmaccal** [comment] 2016-05-20 15:05
It doesn't seem correlated with the temperature.

The temperature when it becomes really slow is ~55 C.  The temperature continues to increase after the pause, topping out at ~65 C, but the simulation runs fine.

And, as I said, it happens reproducibly at the same spot every time.

**Comment by peastman** [comment] 2016-05-20 16:16
This might be working normally.  If you ignore variations and just look at the overall speed in ns/day, is it about what you'd expect given the size of the system?

The thing to understand is that the GPU runs asynchronously.  When you call `step()`, it adds a bunch of kernels to a queue for the GPU to execute.  And then it returns without waiting for them to actually execute.  So when you see that `step()` returns really quickly, that doesn't necessarily mean the time step happened that quickly.  It may just be that there was space in the queue, so it was able to add the kernels without waiting and the actual execution will happen at some time in the future.

There are certain operations that force it to wait until everything in the queue has completed.  For example, copying data from the GPU back to the CPU.  That's what `cuMemcpyDtoH()` does.  When you see that it's taking a really long time, that doesn't necessarily mean the actual copy is taking a long time.  It may just be that there was a lot of work in the queue, and it has to wait for all that work to complete before it can retrieve the results.

**Comment by jlmaccal** [comment] 2016-05-20 16:54
Hmm... I didn't realize that everything was asynchronous, but I'm still not sure if this is a real effect or not. For example, the problem timestep(s) in the example I gave happen 30 steps after a reporter has written the coordinates to a PDB file. So there should only be ~30 steps built up, which shouldn't be taking several seconds to run.

If I run this test while X is running, the interface is completely unresponsive during the period when the slow time step happens. During the regular timesteps, the interface is perfectly responsive. This makes me think the GPU is somehow doing much more work or... something. To be clear, this problem also happens when X is not running, so I don't think it's a conflict with X.

I'm  not sure what sort of performance I should be expecting for this system on a GTX 780. I'm getting ~9 ns/day on 75k atoms with RF and 1.0 nm cutoffs. The DHFR benchmark gives ~300 ns / day on 25k atoms. If a Titan X is 10x faster than a 780, then these numbers might make sense.

Can someone try reproducing this using the repository I posted? I modified `openmm/app/simulation.py` around line 194 to record the step times:

```
            stepsToGo = nextSteps
            while stepsToGo > 10:
                jm_start = time.time()
                self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
                jm_stop = time.time()
                print 'integrated: {}'.format(jm_stop - jm_start)
                stepsToGo -= 10
```

**Comment by jlmaccal** [comment] 2016-05-20 17:25
So, this is definitely not normal. This is output from a MELD run, so I don't have a simple test case to reproduce it.

The state was downloaded at the part where it says `mm:`. You can see that there are a number of sets of 10 steps that take dramatically longer than normal.

```
integrated: 0.000927925109863
integrated: 0.0470809936523
integrated: 0.0512828826904
integrated: 0.000370025634766
mm: 3.83659815788
4.76608800888
integrated: 0.000387907028198
integrated: 0.000355958938599
integrated: 3.42933416367
integrated: 0.000375986099243
integrated: 3.56763100624
integrated: 0.000926971435547
integrated: 0.000998020172119
integrated: 3.56124901772
integrated: 0.000491857528687
integrated: 3.57419705391
integrated: 0.000576972961426
integrated: 0.000695943832397
integrated: 3.56885290146
integrated: 0.000869989395142
integrated: 3.57394099236
integrated: 0.000590085983276
integrated: 0.000750780105591
integrated: 3.5835249424
integrated: 0.000966787338257
integrated: 3.58322620392
integrated: 0.00081992149353
integrated: 1.57710504532
integrated: 0.0531630516052
integrated: 0.000334024429321
integrated: 0.0868830680847
integrated: 0.000922918319702
integrated: 0.000997066497803
integrated: 0.0895538330078
integrated: 0.000687122344971
integrated: 0.0857059955597
integrated: 0.000921964645386
integrated: 0.00086784362793
integrated: 0.0864670276642
integrated: 0.000960826873779
integrated: 0.0870749950409
integrated: 0.000938177108765
integrated: 0.000673055648804
integrated: 0.0883319377899
integrated: 0.000964164733887
integrated: 0.088339805603
integrated: 0.000931978225708
```

**Comment by peastman** [comment] 2016-05-20 17:36
Ok, I have another idea about what might be happening.  Could you confirm something?  In the output above it shows a number of steps that take much longer than usual.  But then after a certain point they stop.  Is that always the case?  That after the simulation has been running for a little while, the problem disappears?

**Comment by jlmaccal** [comment] 2016-05-20 17:48
When I run a normal OpenMM simulation, that might be the case. I just ran a 100 ps simulation and there is only a single set of 10 steps that is really slow.

However, when I run a MELD simulation, the problem continues throughout the simulation. The difference is that I'm doing replica exchange, so I end up calling `setPositions` and `setPeriodicBoxVectors` after the swaps. Could that trigger the problem you are hypothesizing?

**Comment by jlmaccal** [comment] 2016-05-20 18:55
Here are two graphs of 100ps simulations. Each point on the x-axis is 10 steps of the integrator. The y-axis is the time taken for those 10 steps in seconds.

The main difference is that the MELD simulation is using replica exchange, so the coordinates and box vectors are potentially changed every picosecond.

This is with OpenMM:
![omm](https://cloud.githubusercontent.com/assets/108119/15438546/e5e73572-1e89-11e6-8d29-20ab072e472b.png)

This is with MELD:
![meld](https://cloud.githubusercontent.com/assets/108119/15438555/ecce9056-1e89-11e6-9de5-571ad014357e.png)

**Comment by peastman** [comment] 2016-05-20 19:23
Here is a guess about what might be happening.  OpenMM needs to allocate memory on the GPU to hold the neighbor list.  But it doesn't actually know how much to allocate, since the size of the neighbor list is constantly changing, so it just makes a guess.  If it turns out that it didn't allocate enough, the kernel that builds the neighbor list will give up and set a flag indicating it failed.  Then the kernel which actually computes the nonbonded forces will see that flag and not try to use the neighbor list.  It will just use an O(n^2) algorithm, which can be very very slow for large systems.

After the very first time step, OpenMM checks to see if there was enough memory for the neighbor list.  If not, it allocates new memory that's enough for however much was really needed, plus some reasonable padding.  That will hopefully be enough from then on.  As long as the system doesn't change too much, the size of the neighbor list doesn't change much either.  But just to be sure, it checks again every 250 time steps and, as before, allocates more memory if necessary.

Try this.  Go to https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaNonbondedUtilities.cpp#L385-L386.  That's where it checks to see if this is the very first time step and, if so, adjusts the neighbor list size.  Remove the check for `if (context.getComputeForceCount() == 1)` so instead it will do this every time step.  That will slow things down a bit but, if I'm right, it will also eliminate the very slow steps.

**Comment by jlmaccal** [comment] 2016-05-20 20:27
Yep, that's it!

With that line commented out, the run times of each step are much more consistent. When running with "plain" OpenMM, things are about 3% slower. When running with MELD on a single GPU, things are about 5-10% faster. For our multi-gpu / MPI runs of MELD, I suspect this will be dramatically faster, as our REMD implementation only runs as fast as the slowest simulation.

I think I kind of understand how this works. Obviously, you know the best way to fix this, but a few thoughts:
- Maybe make the default guess for the NL size a bit more conservative, like `25` or `30*numAtomBlocks`.
- Perhaps change the check from every 250 steps to every 50 or 100?
- Change the logic to account for changes to the coordinates or box vectors, which seem to trigger the issue.

**Comment by peastman** [comment] 2016-05-20 20:47
Ok, great.  I do have some ideas about how to fix this, but it will take some experimenting.  I'll see what I can come up with.

**Comment by jlmaccal** [comment] 2016-05-20 21:28
Thanks!

FWIW, the Dill group at Stony Brook has identified a huge performance decrease with MELD's REMD simulations when they recently updated from OpenMM 6.2 to a more recent version including cb599d67.

**Comment by peastman** [comment] 2016-05-20 21:32
Do you have reason to think that particular change was responsible?

**Comment by jlmaccal** [comment] 2016-05-20 21:37
I guess not necessarily. They updated from 6.2 to 6.3 and noticed a massive decrease in performance where some replicas seem to randomly take longer than they should to finish their round of simulation.

**Comment by jlmaccal** [comment] 2016-05-20 21:41
More specifically, they updated from 11e5dc7 to 23fa9d95.

**Comment by peastman** [comment] 2016-05-21 00:29
If you can provide a reproducible test case, that would be great.  Otherwise, it's hard to even guess what's going on.

**Comment by jlmaccal** [comment] 2016-05-21 00:32
I'm confused. I'm pretty sure this Dill group's issue is the same as above.

**Comment by peastman** [comment] 2016-05-25 23:59
I think I've got a good fix for this.  Try #1499 and see how it works for you.

**Comment by jlmaccal** [comment] 2016-05-26 00:25
Thanks, I'll check it out tomorrow.

**Comment by jlmaccal** [comment] 2016-05-26 21:49
Here are the results using #1499.

It's clearly much better, although there is still a bit of a strange pattern happening where something is taking longer and longer as the simulation progresses. It could be that this is something trivial, like density of system increasing due to pressure coupling.

![fixed](https://cloud.githubusercontent.com/assets/108119/15591256/210feeb8-2359-11e6-8e80-5dd564dd690a.png)

**Comment by peastman** [comment] 2016-05-26 21:55
Ok, I'll go ahead and merge it.  It would be good to figure out what else is going on.  Do you see the same pattern if you use the CPU platform?  It might also be useful to run it with a profiler and see if you can tell where that time is being spent.  Are you sure it's in OpenMM code?

**Closed** 2016-05-26 21:55 UTC

**Comment by jlmaccal** [comment] 2016-05-26 22:00
> Ok, I'll go ahead and merge it. It would be good to figure out what else is going on. Do you see the same pattern if you use the CPU platform? It might also be useful to run it with a profiler and see if you can tell where that time is being spent. Are you sure it's in OpenMM code?
> 

I’ll look into it, but I’m sure it’s openmm code. I’ve modified the openmm python wrappers to report the time it takes to finish each call to `integrator.step(10)`, which is what I’m plotting.

The main difference in the MELD simulations, is that the coordinates and box vectors are being changed every picosecond due to replica exchange moves.
