### ISSUE TITLE
We should report PME grid dimensions for AmoebaMultipoleForce

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#761] opened 2014-12-28 17:18 UTC
Hi there,

I think it would be very useful if we could query the PME grid dimensions for the `AmoebaMultipoleForce` in a `Context`.  Currently there is no way to get the grid dimensions if the user specifies `ewaldErrorTolerance` - the grid dimensions are calculated automatically when creating the Context, but if I call `simulation.context.getSystem().getForce(force_num).getPmeGridDimensions()` the return value is `(0,0,0)`.

On the CUDA platform, the grid dimensions are automatically set in `AmoebaCudaKernels.cpp` if the user doesn't provide them explicitly.  If the `AmoebaMultipoleForce` argument weren't declared as `const`, then we could call `AmoebaMultipoleForce.setPmeGridDimensions()` and the user could query them from the application layer.  This seems to go against the current design, does anyone have ideas that might work?

Thanks,

- Lee-Ping 

Below is the code snippet for what I'm referring to.

```
CudaCalcAmoebaMultipoleForceKernel::initialize(const System& system, const AmoebaMultipoleForce& force)
        ...
        force.getPmeGridDimensions(pmeGridDimension);
        if (pmeGridDimension[0] == 0 || alpha == 0.0) {
            // LPW This code calculates the grid dimensions automatically
            NonbondedForce nb;
            nb.setEwaldErrorTolerance(force.getEwaldErrorTolerance());
            nb.setCutoffDistance(force.getCutoffDistance());
            NonbondedForceImpl::calcPMEParameters(system, nb, alpha, gridSizeX, gridSizeY, gridSizeZ);
            gridSizeX = findFFTDimension(gridSizeX);
            gridSizeY = findFFTDimension(gridSizeY);
            gridSizeZ = findFFTDimension(gridSizeZ);
            // LPW I wish I could do this
            pmeGridDimension[0] = gridSizeX;
            pmeGridDimension[1] = gridSizeY;
            pmeGridDimension[2] = gridSizeZ;
            force.setPmeGridDimensions(pmeGridDimension);
            // LPW
        } else {
            gridSizeX = pmeGridDimension[0];
            gridSizeY = pmeGridDimension[1];
            gridSizeZ = pmeGridDimension[2];
        }
        defines["EWALD_ALPHA"] = cu.doubleToString(alpha);
        defines["SQRT_PI"] = cu.doubleToString(sqrt(M_PI));
        defines["USE_EWALD"] = "";
        defines["USE_CUTOFF"] = "";
        defines["USE_PERIODIC"] = "";
        defines["CUTOFF_SQUARED"] = cu.doubleToString(force.getCutoffDistance()*force.getCutoffDistance());
```

Thanks,

- Lee-Ping

**Comment by jchodera** [comment] 2015-01-03 20:23
+1 for this---it would very much help reproducibility among codes.

**Comment by leeping** [comment] 2015-01-04 05:15
Right - for the time being, I've hacked it to print the PME grid but it shouldn't be hard to feed this information back into the System object.

**Comment by swails** [comment] 2015-01-04 05:27
> On the CUDA platform, the grid dimensions are automatically set in AmoebaCudaKernels.cpp if the user doesn't provide them explicitly. If the AmoebaMultipoleForce argument weren't declared as const, then we could call AmoebaMultipoleForce.setPmeGridDimensions() and the user could query them from the application layer. This seems to go against the current design, does anyone have ideas that might work?

Querying them from the `System` object would seem to go against the grain of some OMM design principles.  @peastman has already laid out reasons why creating contexts (more specifically, `ForceImpl`s) should _not_ modify the underlying system or forces in #763.  Serialization would behave unexpectedly and asymmetrically [1] which is a bad thing.

This is also a feature I would also like, since I routinely compare results across codes, but I think we are going to wind up needing some way to extract those parameters from the `Context`, not the `System`.  After all, PME grid dimensions will be platform-specific (since optimal grid prime factors for the FFT grid vary based on the platform-dependent FFT implementation).

Probably easier would be to have some kind of API addition to `AmoebaMultipoleForce` in which you could request optimal PME parameters based on your Ewald tolerance and starting coordinates (so that you could then turn around and set those parameters explicitly).

[1] Let's say we create context 1 and context 2 with very different starting coordinates.  It is possible that the starting grid dimensions would be different from each other, in which case the order that you created the contexts matters (since context 2 would "inherit" the parameters from context 1).

**Comment by peastman** [comment] 2015-01-05 18:29
Note that if you just want to know the "ideal" values, the formulas are given in section 19.6.5 of the manual.  But if you want to know the exact values actually being used, then those are platform specific for the reasons @swails pointed out.  Perhaps AmoebaMultipoleForce and NonbondedForce could each have an alternate version of getPMEParameters() that takes a Context as an additional argument, and returns the specific values being used in that Context?

**Comment by jchodera** [comment] 2015-01-05 18:32
> Perhaps AmoebaMultipoleForce and NonbondedForce could each have an alternate version of getPMEParameters() that takes a Context as an additional argument, and returns the specific values being used in that Context?

That sounds like a good solution!

**Comment by swails** [comment] 2015-01-05 18:47
I agree with @jchodera.  It is intuitive and succinct -- sounds like a good solution.

**Comment by peastman** [comment] 2015-01-05 18:50
@leeping if you like that solution, could you enter it in the feature request tracker?  I probably won't be able to get to this for a month or two, and I don't want it to be forgotten.

**Comment by leeping** [comment] 2015-01-06 13:10
Sounds good, I'll do that.

**Comment by jchodera** [comment] 2015-08-30 21:43
This is probably subsumed by #1111.

**Comment by peastman** [comment] 2015-08-31 17:46
Agreed.  I'll close this, since the two are duplicates.

**Closed by peastman** 2015-08-31 17:46 UTC
