### ISSUE TITLE
Unstable simulation with GPU

### ISSUE THREAD

**Issue by isjoung** [pandegroup/openmm#1486] opened 2016-05-11 17:58 UTC
Hello,
This is a kind of simple standard protocol. The backbone of the script is basically built by OpenMM script builder. The system has a small protein in water box. Interestingly, temperature is stable with CPU but not with GPU(CUDA/OpenCL). The test code, input files and output files are attached. In short, on CUDA, the temperature rises fast and soon the system crashes or keeps very high temperature. Is there a way to fix this problem?
 
[unstable.tar.gz](https://github.com/pandegroup/openmm/files/259846/unstable.tar.gz)

```python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

def add_positional_rest(prmtop,system,positions):
    topology = prmtop.topology
    pforce = mm.CustomExternalForce('k*((x-x0)^2+(y-y0)^2+(z-z0)^2)')
    pforce.addGlobalParameter('k',100.0)
    pforce.addPerParticleParameter('x0')
    pforce.addPerParticleParameter('y0')
    pforce.addPerParticleParameter('z0')
    count = 0
    for atom in topology.atoms():
        resname = atom.residue.name
        atmname = atom.name
        if    atmname[0] == 'H' or atmname == 'Na+' or atmname == 'Cl-' \
           or resname == 'HOH' or resname == 'WAT':
            continue
        ind = atom.index
        x0, y0, z0 = ( positions[ind] ).value_in_unit(unit.nanometer)
        pforce.addParticle(atom.index,(x0,y0,z0))
        count += 1
    system.addForce(pforce)
    print( 'The number of positional restraints: %d'%count )

prmtop = app.AmberPrmtopFile('model.prmtop')
inpcrd = app.AmberInpcrdFile('model.inpcrd')

system = prmtop.createSystem(nonbondedMethod=app.PME,
    nonbondedCutoff=1.0*unit.nanometers, constraints=app.HBonds, rigidWater=True,
    ewaldErrorTolerance=0.0005)
integrator = mm.VerletIntegrator(0.002*unit.picoseconds)
integrator.setConstraintTolerance(0.00001)
system.addForce(mm.AndersenThermostat(300*unit.kelvin, 1.0/unit.picoseconds))
system.addForce(mm.MonteCarloBarostat(1.0*unit.atmospheres, 300*unit.kelvin, 25))
add_positional_rest(prmtop,system,inpcrd.positions)

platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'double'}
simulation = app.Simulation(prmtop.topology, system, integrator, platform,
    properties)
simulation.loadState('input.xml')

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)

simulation.reporters.append(app.StateDataReporter(stdout, 10, step=True,
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True,
    speed=True, totalSteps=10000, separator='\t'))

print('Running Production...')
simulation.step(10000)
print('Done!')
```

**Comment by swails** [comment] 2016-05-11 18:02
This is probably because the GPU platforms image the coordinates and the CPU platforms don't.

Use `periodicdistance` in `CustomExternalForce` instead of computing the raw distance.  The docs for `CustomExternalForce` [has a note about taking care with PBC](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html#)

**Comment by isjoung** [comment] 2016-05-11 18:20
I didn't know that ExternalForce can be affected by the periodic images. It is good to know that. But unfortunately the symptom is same even after commenting out the addParticle line. (Meaning that there is no CustomExternalForce)
```python
#        pforce.addParticle(atom.index,(x0,y0,z0))
```

**Comment by peastman** [comment] 2016-05-11 19:04
I'm looking into it now.  The problem seems to be in some way related to PME reciprocal space calculations.  If I switch the nonbonded method to CutoffPeriodic it goes away.  If I increase the cutoff (so more work gets done in direct space and less in reciprocal space), the temperature increases more slowly.  If I decrease the cutoff (so less work gets done in direct space and more in reciprocal space), the temperature increases faster.  I also verified that the same problem occurs with OpenCL, and that it doesn't depend on the precision mode.

I'll let you know as I find more.

**Comment by peastman** [comment] 2016-05-11 21:46
I found the problem.  It's a bug in the handling of PME with triclinic boxes.  I'll send a PR with the fix shortly.

**Comment by peastman** [comment] 2016-05-11 22:50
Could you verify that #1487 fixes your problem?

I've been trying to create a simplified test case for this problem, but so far all my attempts have been unsuccessful.  There's some combination of factors in your file that was triggering it, and I haven't been able to reproduce it in any simpler system.

**Comment by isjoung** [comment] 2016-05-12 07:31
I changed the raw distance calculation to `periodicdistance` and applied the patch. Then, I don't see the previous outrageous temperature any more but it is sill not so satisfactory. No matter whether it is 'double' or 'mixed', the temperature of CUDA platform is off while the temperature of CPU platform looks fine.
![plot](https://cloud.githubusercontent.com/assets/7530585/15207018/2ac93988-185e-11e6-9c51-5aab35a1a7e7.png)

**Comment by isjoung** [comment] 2016-05-12 08:39
I also tried to increase the collision frequency of the thermostat.

platform | thermostat freq | average temp (20000-100000 steps)
---- | ---- | ----
CPU | 1./ps | 301.8
CUDA double | 1./ps | 318.2
CUDA mixed | 1./ps | 317.4
CUDA mixed | 5./ps | 318.4
CUDA mixed | 100./ps | 317.7

I am afraid that the temperature of CPU platform is also off a bit.

**Comment by peastman** [comment] 2016-05-13 17:55
Try again--I think I've got it properly fixed now.

**Comment by isjoung** [comment] 2016-05-14 14:14
The same test was carried out.

At this time, I compared the result with the simulation performed by AMBER. For the openmm version, the force constant of positional constant was 10.0 (different from the number in the source code above), The unit converted constant for AMBER should be 0.0239. This is the AMBER input:
```
 Equilibration
&cntrl
 !restart
 irest = 0, ntx=1

 ! temperature
 temp0 = 300.0, tempi = 0.0, ntt=3, gamma_ln=1.0,

 ! pressure / boundary
 ntp = 1, taup = 5.0, ntb = 2

 ! SHAKE
 ntf    = 2,  ntc  = 2, tol = 1d-5,

 ! print
 ntpr = 10, ntwr = 5000, ntwx=500,

 ! cutoff
 cut    = 10.0,

 ! md steps (200 ps)
 imin   = 0,       nstlim = 100000,

 ! time step
 dt = 0.002,

 ! positional restraints
 ntr = 1, restraint_wt = 0.0239, restraintmask = ':* & !@H= & !@Na+ & !@Cl- & !:WAT',
&end
```

platform | avg temp (20000-70000 steps)
---- | ----
CPU | 302.38 (+/- 2.17)
CUDA mixed | 301.86 (+/- 2.19)
pmemd.cuda_SPFP | 299.92 (+/- 2.20)

The fluctuations(stdev) are similar for all the three cases (~2.2 degree), but averages are different.  PMEMD is only off by 0.08 degree but both of the openmm results are slightly high. I think this difference is still a warning. By the way, CPU and CUDA platforms seem to generate similar results after the second patch.

**Closed** 2016-05-16 02:24 UTC

**Comment by peastman** [comment] 2016-05-16 02:27
Thanks!  I've merged the fix.  I'll look into the temperature later, but since it's within one standard deviation of the expected value, I'm not too worried about it.

**Comment by peastman** [comment] 2016-05-16 20:00
I've been running lots of tests with your simulation, changing different parameters to see what affects the temperature.  First, here are some things that I found had no significant effect:

- Decreasing the constraint tolerance to 1e-6.
- Decreasing the Ewald error tolerance to 5e-5.
- Turning on the LJ switching function.
- Running in double precision mode.

Those are all the main sources of numerical error.  None of them seem to be the issue here.

I found two things that did matter:

- Decreasing the step size to 1 fs.  With that change, three runs of the test reported average temperatures of 300.2, 299.9, and 299.6.
- Constraining all bonds, no just ones with hydrogens.  Three runs reported temperatures of 299.6, 299.7, and 298.0.

So this looks to me like just integrator error, nothing specific to the code.  I don't know why Amber would report a lower temperature with identical step size and constraints.  Did you try repeating it a few times to see how consistent it was?

**Comment by jchodera** [comment] 2016-05-16 20:09
Could Amber be using a constraint tolerance that pulls energy out of the
system?

**Comment by isjoung** [comment] 2016-05-17 05:24
I extended simulations longer. The following table shows average temperature, deviation from 300.0, and standard deviation at different intervals.

time | mixed 2fs | mixed 1fs | amber 2fs
---- | ---- | ---- | ----
200 ps-400 ps  | 301.85 / 1.85 (2.20)  | 300.74 / 0.74 (2.10)  | 299.65 / -0.35 (2.12)
400 ps-600 ps  | 302.78 / 2.78 (2.14)  | 300.89 / 0.89 (2.13)  | 299.97 / -0.03 (2.14)
600 ps-800 ps  | 302.42 / 2.42 (2.11)  | 300.64 / 0.64 (2.18)  | 299.83 / -0.17 (2.10)
800 ps-1000 ps  | 302.36 / 2.36 (2.16)  | 300.55 / 0.55 (2.11)  | 300.02 / 0.02 (2.09)
1000 ps-1200 ps  | 302.09 / 2.09 (2.06)  | 300.45 / 0.45 (2.21)  | 300.06 / 0.06 (2.25)
1200 ps-1400 ps  | 302.28 / 2.28 (2.14)  | 300.77 / 0.77 (2.17)  | 300.00 / -0.00 (2.20)
1400 ps-1600 ps  | 302.40 / 2.40 (2.24)  | 300.64 / 0.64 (2.09)  | 299.75 / -0.25 (2.15)
1600 ps-1800 ps  | 302.63 / 2.63 (2.25)  | 300.59 / 0.59 (2.10)  | 300.06 / 0.06 (2.19)
1800 ps-2000 ps  | 302.20 / 2.20 (2.13)  | 300.95 / 0.95 (2.19)  | 299.72 / -0.28 (2.12)
200 ps-2000 ps  | 302.33 / 2.33 (2.17)  |  300.69 / 0.69 (2.15)  |  299.90 / -0.10 (2.16)

All of the results above were generated by CUDA. I am not sure if even long simulation is necessary in order to compare them more accurately. _T_-test (non-equivalent variance/two-tail) tells that any pair of data sets has almost zero _p_-value, which means that all the three data sets are statistically different. Time step does affect the behavior a lot and shorter time step reduced the deviation. However, it looks like openmm results are always positively deviated?

**Comment by peastman** [comment] 2016-05-17 18:15
Like @jchodera I'm suspicious of the Amber numbers, and I especially wonder about constraints.  What tolerance are you using for them there?  Also, do you know what algorithm it uses for them?

Let me explain why I'm suspicious.  This will be a bit of a treatise, so please bear with me. :)

Any source of random error in a simulation will tend to increase the temperature.  It acts just like the random force in the Langevin integrator.  The simulation doesn't care whether the random perturbations are coming from a PRNG you added intentionally or some other source you'd didn't intend to be there.  The effect is the same.  So your thermostat may be set to 300K, but if you have any sources of error at all in your simulation, the effective temperature will be a bit higher.  You try to minimize sources of error so it won't be too much higher.

Random errors fall into two categories: numerical errors, which come from approximations and inaccuracies in your code, and integration error, which is inherent in the integration algorithm.  Numerical error is specific to your code.  Different codes may have different levels of numerical error if they implement the same algorithm slightly differently.  But integration error just comes from the fact that you're using a finite step size.  Any two codes that use the same algorithm with the same parameters will have exactly the same level of integration error.

In this case, it really looks to me like the temperature increase is coming from integration error, not numerical error.  There are two reasons I think that.

1. I tried everything I could think of to reduce numerical error, and they made no difference.

2. When I reduced the integration error by cutting the time step in half, that had a large effect.

People who run MD simulations tend to be pretty aggressive with their time steps, because they want to run as long simulations as they can.  How did 2 fs get chosen as a standard step size?  You might hope someone looked for the largest step size that had negligible effect on temperature, but that's not at all the case.  Actually, they looked for the largest step size that would reliably run without blowing up!  So it would be quite surprising if it *didn't* have some measurable effect on temperature.

So why is Amber *not* showing an elevated temperature?  There are a couple of possibilities that occur to me.  The first is that you aren't really using exactly the same integration method with identical parameters.  For example, are you using the same friction coefficient in both OpenMM and Amber?  Higher friction will reduce the effect of random errors on the temperature.

The other possibility is that the Amber simulations have some kind of systematic error.  Random errors always increase the temperature, but systematic errors can either increase or decrease it.  And there's one very important example of that: constraint tolerance.  Constrained dynamics only conserves energy when the constraints are always satisfied to infinite precision.  If you only converge them to finite precision, the effect is to pull energy out of the system and decrease the temperature.  Perhaps you're using a larger tolerance in Amber than in OpenMM?  Also, OpenMM uses the analytic SETTLE method for rigid water, so the constraint tolerance only affects constraints within the protein.  I don't know what Amber does.  If it's using something iterative for the water as well, then the constraint tolerance will have a much bigger effect.

**Comment by swails** [comment] 2016-05-17 19:09
Amber uses SETTLE as well.  Is it also possible that OpenMM and Amber compute the kinetic energy slightly differently?  Amber gets the velocities a half time-step behind and a half time-step ahead (we're doing something between leap-frog and VVerlet, I believe), then averages those to get the velocities at our current time-step.  Is that exactly what OpenMM does with its Langevin integrator?

I believe I recall a past conversation with someone who mentioned that (and maybe why) Amber's integrator tended to hit temperatures slightly under the target.

**Comment by rmcgibbo** [comment] 2016-05-17 19:19
Curious. What's the reason for computing the temperature like that? For computing the average temperature over an interval substantially longer than 1fs, it seems unnecessary to "correct" for the half-step like that. I guess that could be more useful if you're looking at cross-correlations between different per-frame observables or something?

**Comment by swails** [comment] 2016-05-17 19:25
That's done to ensure that the kinetic energy corresponds to the same configuration that the potential energy does.  This is most important when you're trying to monitor energy conservation in your integrator (if K and U correspond to different time-steps, you can't really use those to assert much about how well you conserve energy).

The potential energy is computed from the positions at time step t, while the velocities that have been computed correspond to the positions at t-0.5dt.  They are propagated by a time-step to give velocities at t+0.5dt.  Averaging them gives a much better estimate of the kinetic energy at time t.  This is classic leap-frog and, IIRC, is described in allen & tildesley.

My knowledge of integrators is a bit rusty, so I don't know all the finer details off the top of my head anymore.  But once upon a time I did walk through the Amber integrator in pretty fine detail to understand everything it was doing.

**Comment by jchodera** [comment] 2016-05-17 19:28
That's an excellent point, @swails and @rmcgibbo. I actually fixed a bug in AMBER's Andersen thermostat long ago---someone had coded the kJ/mol to kcal/mol conversion as 4.814 instead of 4.184.  I also noticed that the velocities were randomized with half-timestep-lagged velocities---rather than on the timestep, as Anderson requires.  In practice, one should randomize the velocities and then back up by half a timestep in order to get the correct Andersen thermostat implementation that is isomorphic with Andersen applied to velocity Verlet.  I made this change to AMBER, but I'm not sure it survived. I don't think it is done this way in OpenMM since AndersenThermostat has no knowledge of whether the integrator is a leapfrog or velocity Verlet.

> For computing the average temperature over an interval substantially longer than 1fs, it seems unnecessary to "correct" for the half-step like that.

The "velocities" in these integrators are all fictitious, and are really just intermediate variables in a position integration scheme that is accurate to higher order in position integration. Using the half-timestep or on-timestep values for velocity estimates result in different accuracies and biases. We did some of this analysis in our VVVR paper for a VV-based Langevin integrator:

http://pubs.acs.org/doi/abs/10.1021/jp411770f

**Comment by rmcgibbo** [comment] 2016-05-17 19:28
Right. I understand that might. I would just think the default thing would be to back-propagate the velocity by a half a step instead of averaging.

**Comment by jchodera** [comment] 2016-05-17 19:53
>  I would just think the default thing would be to back-propagate the velocity by a half a step instead of averaging.

For OpenMM or AMBER?

**Comment by rmcgibbo** [comment] 2016-05-17 19:57
@jchodera: "Default thing" was sloppy language on my part. I really meant that I assume that propagating the velocity either forward or backward by a half-step would be the _correct_ method to compute the kinetic energy and temperature for leapfrog.

**Comment by jchodera** [comment] 2016-05-17 20:03
I believe that is the simplest way to get a reasonable velocity estimator (or results identical with velocity Verlet) presuming you have RATTLE implemented.  But if you only have SHAKE, I don't believe you can do this.

**Comment by swails** [comment] 2016-05-17 20:05
That would make sense.  RATTLE is what you use for VV IIUC, but Amber only has SHAKE (and SETTLE).

**Comment by peastman** [comment] 2016-05-17 21:33
The kinetic energy reported by OpenMM is precisely what you would get if you were using velocity Verlet with RATTLE.  It computes the forces, uses them to advance the velocities by half a time step, and then applies constraints to them.

I'm pretty sure that averaging the velocities from two time steps will systematically underestimate them.  Given any function sampled at discrete intervals, averaging adjacent samples is equivalent to applying a lowpass filter, so you're basically throwing out the highest frequency components.  Or if you prefer a more geometrical illustration, think of a particle moving in a circle in the XY plane.  Its velocity also follows a circular path in the v_x v_y plane.  Now take two points on that circle and average them.  The result will lie inside the circle.  Its magnitude will be smaller than the radius of the actual circle.

**Comment by isjoung** [comment] 2016-05-18 04:23
Wow, all the comments were very helpful. I understand that all the implementation of the detailed parts of the simulation engine are not exactly identical between openmm and amber. I was just worried that there is something I missed. It makes sense that different ways of evaluating kinetic energy may cause the difference.

**Comment by peastman** [comment] 2016-05-18 16:39
I'd still like to make sure we really understand what's going on.  Could you check the parameters I mentioned, such as friction coefficient and constraint tolerance?  What values are you using for them in Amber?

**Comment by isjoung** [comment] 2016-05-19 01:50
I am sorry that I missed it.

```
ntt=3, gamma_ln=1.0
```
Use Langevin dynamics(ntt=3) with the collision frequency 1.0/ps (gamma_ln=1.0).

```
 ntf    = 2,  ntc  = 2, tol = 1d-5,
```
Bond involved in hydrogens are constrained(ntc=2) and bond interactions involving hydrogen atoms are omitted (ntf=2). Relative geometrical tolerance for coordinate resetting in shake was 1.0e-5 Angstrom (tol=1d-5).

`integrator.setConstraintTolerance(0.00001)` maybe corresponds to `tol=1d-4`? Also, Verlet integrator and Andersen thermostat agree better with `ntt=2, vrand=500` (Andersen / velocity randomization at every 500 step(=1/ps))

FYI, I reran the AMBER simulation with the changed parameters. In the same way, I reran OPENMM simulation with the modified parameters:
```python
#integrator = mm.VerletIntegrator(0.002*unit.picoseconds)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 
    2.0*unit.femtoseconds)
integrator.setConstraintTolerance(0.000001)
#system.addForce(mm.AndersenThermostat(300*unit.kelvin, 1.0/unit.picoseconds))
system.addForce(mm.MonteCarloBarostat(1.0*unit.atmospheres, 300*unit.kelvin, 25))
```
The new setup might agree better with the previous AMBER run.

time | openmm | amber
---- | ---- | ----
200 ps-400 ps  | 299.84 / -0.16 (2.22)  | 300.38 / 0.38 (2.09)
400 ps-600 ps  | 299.93 / -0.07 (2.13)  | 299.90 / -0.10 (2.09)
600 ps-800 ps  | 299.98 / -0.02 (2.15)  | 300.29 / 0.29 (2.16)
800 ps-1000 ps  | 300.20 / 0.20 (2.22)  | 299.95 / -0.05 (2.06)
1000 ps-1200 ps  | 299.87 / -0.13 (2.13)  | 300.34 / 0.34 (2.09)
1200 ps-1400 ps  | 299.94 / -0.06 (2.21)  | 299.69 / -0.31 (2.08)
1400 ps-1600 ps  | 299.81 / -0.19 (2.10)  | 300.01 / 0.01 (2.14)
1600 ps-1800 ps  | 300.05 / 0.05 (2.13)  | 300.16 / 0.16 (2.10)
1800 ps-2000 ps  | 300.17 / 0.17 (2.12)  | 299.73 / -0.27 (2.08)
200 ps-2000 ps  | 299.98 / -0.02 (2.16)  |  300.05 / 0.05 (2.11)

Hmm... interesting result. Openmm with Langevin integrator looks fine. AMBER with andersen thermostat also looks fine.

**Comment by peastman** [comment] 2016-05-19 17:21
Just to make sure I understand: you were previously using different thermostats (Andersen in OpenMM, Langevin in Amber).  When you switched to using Langevin in both, the results agree.  Is that correct?

Andersen and Langevin each have an adjustable time constant, but they don't really mean exactly the same thing.  So if you set the Langevin friction and the Andersen collision frequency to the same value, that won't necessarily produce exactly the same effect.  Also, "Andersen thermostat" really refers to two slightly different algorithms.  In some programs, it replaces a small fraction of velocities on every time step.  In others, it infrequently replaces all velocities at once.  They're both reasonable ways of doing it, but the effect may be slightly different.  OpenMM uses the former method.  I don't know which one Amber uses.

**Comment by swails** [comment] 2016-05-19 18:15
Amber uses the latter.

**Comment by isjoung** [comment] 2016-05-20 07:01
>Just to make sure I understand: you were previously using different thermostats (Andersen in OpenMM, Langevin in Amber). When you switched to using Langevin in both, the results agree. Is that correct?

Yes, that is correct.
