### ISSUE TITLE
The GPU MD speed is getting slower and slower

### ISSUE THREAD

**Issue by zhengmin317** [pandegroup/openmm#1412] opened 2016-03-10 04:10 UTC
I was running a log md simulation of 50,000,000 steps.
I found out the gpu OpenCL MD speed getting slower and slower from ~120 ns/day to ~60 ns/day, please see the output file [md_2.txt](https://github.com/pandegroup/openmm/files/166507/md_2.txt).

However when I set the md steps 20,000,000, the speed stayed around 120 ns/day.

**Comment by jchodera** [comment] 2016-03-10 13:53
Could you share the input files you used?

**Comment by jchodera** [comment] 2016-03-10 13:54
Also, which GPU were you running on?

**Comment by zhengmin317** [comment] 2016-03-11 09:19
I used charmm-gui to do all the set up.
The input file is  [openmm_run.py.txt](https://github.com/pandegroup/openmm/files/168745/openmm_run.py.txt)




Here is the gpu info:
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  On   | 0000:03:00.0     Off |                  N/A |
| 48%   77C    P2   154W / 250W |    138MiB /  6143MiB |     81%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 980 Ti  On   | 0000:81:00.0     Off |                  N/A |
| 44%   73C    P2   148W / 250W |    132MiB /  6143MiB |     46%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by peastman** [comment] 2016-03-16 17:21
What happens if you let it run until it slows down, then save a checkpoint, stop the simulation, and resume from the checkpoint?  I'm wondering whether the slowdown is caused by something in the code (which would be reset by restarting it) or by a change in the system you're simulating.  Also, is there any obvious change in the simulation at the point it slows down, such as a protein unfolding or something like that?

**Comment by zhengmin317** [comment] 2016-03-16 21:28
@peastman 
You are right. The md simulation is for an RNA unfolding.
But why the RNA unfolding will make the md speed slower and slower?

**Comment by peastman** [comment] 2016-03-16 21:49
It has to do with how OpenMM's GPU platforms implement nonbonded interactions.  Instead of building a separate neighbor list for every atom, it builds a "coarse grained" neighbor list for blocks of 32 atoms.  That works best when everything is tightly packed together.  You want each block of 32 atoms (in the order they're defined along the chain) to be as compact as possible.  As the molecule unfolds, those blocks become less compact, which means more atoms have to be included in the neighbor list for each block.

Here's a paper describing an earlier version of the algorithm: http://onlinelibrary.wiley.com/doi/10.1002/jcc.21413/abstract.  It's evolved some since then, but much of the discussion is still accurate.

**Comment by zhengmin317** [comment] 2016-03-17 07:05
@peastman 
Does this mean that  openmm can not been used to simulate systems involved  in large configuration changes?

**Comment by peastman** [comment] 2016-03-17 16:57
Sure it can.  It just means the performance is a bit better in the folded state than the unfolded state.

**Comment by peastman** [comment] 2016-04-11 18:55
Closing this, since it's not actually a bug.

**Closed by peastman** 2016-04-11 18:55 UTC
